-- KAMATNE STOPE - VEZANE SAMO ZA PROIZVOD
CREATE TABLE KAMATNE_STOPE (
    STOPA_ID            INTEGER         NOT NULL,
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    RAZINA_RAZREDA      SMALLINT        NOT NULL,
    SALDO_OD            DECIMAL(15,2)   NOT NULL,
    SALDO_DO            DECIMAL(15,2),
    KAMATA_STOPA        DECIMAL(5,4)    NOT NULL,
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    METODA_IZRACUNA     CHAR(3)         DEFAULT 'DAN',
    
    CONSTRAINT PK_KAMATNE_STOPE PRIMARY KEY (STOPA_ID),
    CONSTRAINT FK_KAMATA_PROIZVOD FOREIGN KEY (PROIZVOD_KOD) 
        REFERENCES PROIZVOD_MASTER (PROIZVOD_KOD),
    CONSTRAINT CHK_METODA_KAMATA CHECK (METODA_IZRACUNA IN ('DAN', 'MJE', 'KVA', 'GOD')),
    CONSTRAINT CHK_RAZINA_RAZRED CHECK (RAZINA_RAZREDA > 0),
    CONSTRAINT CHK_SALDO_OPSEG CHECK (SALDO_DO IS NULL OR SALDO_DO > SALDO_OD),
    CONSTRAINT CHK_KAMATA_DATUMI CHECK (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA > DATUM_VAZENJA)
);