-- ==================================================================================
-- BRISANJE POSTOJECIH OBJEKATA (REVERSE FK DEPENDENCY ORDER)
-- Platform: IBM DB2 z/OS v13
-- Note: IF EXISTS works on z/OS v12+. Remove if running on older version.
-- ==================================================================================

SET CURRENT SCHEMA = 'BANKING_TEST';

-- Transaction tables
DROP TABLE IF EXISTS GLAVNA_KNJIGA;
DROP TABLE IF EXISTS RED_TRANSAKCIJA;
DROP TABLE IF EXISTS TRANSAKCIJE;
DROP TABLE IF EXISTS BLOKADE;

-- Dependent tables
DROP TABLE IF EXISTS RACUN_PROIZVODI;
DROP TABLE IF EXISTS KLIJENT_DOKUMENTI;
DROP TABLE IF EXISTS KLIJENT_KONTAKTI;
DROP TABLE IF EXISTS KLIJENT_ADRESE;
DROP TABLE IF EXISTS KAMATNE_STOPE;

-- Master entities
DROP TABLE IF EXISTS RACUNI;
DROP TABLE IF EXISTS KLIJENTI;
DROP TABLE IF EXISTS PROIZVOD_MASTER;

-- Reference tables
DROP TABLE IF EXISTS IZVORNI_SUSTAV_REF;
DROP TABLE IF EXISTS TRANSAKCIJA_TIP_REF;
DROP TABLE IF EXISTS TIP_RACUNA_REF;
DROP TABLE IF EXISTS STATUS_REF;
DROP TABLE IF EXISTS RIZIK_OCJENA_REF;
DROP TABLE IF EXISTS POSLOVNICE;

COMMIT;