-- =====================================================
-- TRANSAKCIJE - POJEDNOSTAVLJENO
-- =====================================================
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE TABLESPACE TSTRANS IN "BANKTEST" USING STOGROUP SYSDEFLT;
-- TRANSAKCIJE
CREATE TABLE TRANSAKCIJE (
    TRANSAKCIJA_ID      CHAR(20)        NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    KOD_TRANSAKCIJE     CHAR(4)         NOT NULL,
    IZNOS               DECIMAL(15,2)   NOT NULL,
    DATUM_TRANSAKCIJE   DATE            NOT NULL,
    DATUM_KNJIZENJA     DATE            NOT NULL,
    OPIS                VARCHAR(50),
    POZIV_NA_BROJ       VARCHAR(20),
    TEKUCI_SALDO        DECIMAL(15,2)   NOT NULL,
    IZVORNI_SUSTAV      CHAR(6)         NOT NULL,
    STATUS              CHAR(1)         DEFAULT 'K',
    POSLOVNICA_UNOS     CHAR(4)         NOT NULL,
    OPERATER_UNOS       VARCHAR(10)     NOT NULL,
    VREMENSKI_ZAPIS     TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    
    CONSTRAINT PK_TRANSAKCIJE PRIMARY KEY (TRANSAKCIJA_ID),
    CONSTRAINT FK_TRN_RACUN FOREIGN KEY (RACUN_BROJ) 
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_TRN_TIP FOREIGN KEY (KOD_TRANSAKCIJE) 
        REFERENCES TRANSAKCIJA_TIP_REF (TRN_TIP_KOD),
    CONSTRAINT FK_TRN_SUSTAV FOREIGN KEY (IZVORNI_SUSTAV) 
        REFERENCES IZVORNI_SUSTAV_REF (SUSTAV_KOD),
    CONSTRAINT FK_TRN_POSLOVNICA FOREIGN KEY (POSLOVNICA_UNOS) 
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_TRN_STATUS CHECK (STATUS IN ('K', 'P', 'O', 'G'))
) IN BANKTEST.TSTRANS;