-- KLIJENT DOKUMENTI - SIGURNOST
CREATE TABLE KLIJENT_DOKUMENTI (
    DOKUMENT_ID         BIGINT          NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_DOKUMENTA       CHAR(3)         NOT NULL,
    BROJ_DOKUMENTA      VARCHAR(20)     NOT NULL,
    IZDAVATELJ          VARCHAR(50),
    DATUM_IZDAVANJA     DATE,
    DATUM_ISTEKA        DATE,
    PUTANJA_DATOTEKE    VARCHAR(200),
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_UPLOAD        TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    
    CONSTRAINT PK_KLIJENT_DOKUMENTI PRIMARY KEY (DOKUMENT_ID),
    CONSTRAINT FK_DOKUMENT_KLIJENT FOREIGN KEY (KUPAC_ID) 
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT CHK_DOKUMENT_TIP CHECK (TIP_DOKUMENTA IN ('LK', 'PAS', 'VLZ', 'OST')),
    CONSTRAINT CHK_DOKUMENT_STATUS CHECK (STATUS IN ('A', 'N', 'I'))
);