-- KLIJENT KONTAKTI - NORMALIZIRANO
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE TABLE KLIJENT_KONTAKTI (
    KONTAKT_ID          BIGINT          NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_KONTAKTA        CHAR(2)         NOT NULL,
    VRIJEDNOST_KONTAKTA VARCHAR(50)     NOT NULL,
    GLAVNI_KONTAKT      CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_OD            DATE            NOT NULL,
    DATUM_DO            DATE,
    
    CONSTRAINT PK_KLIJENT_KONTAKTI PRIMARY KEY (KONTAKT_ID),
    CONSTRAINT FK_KONTAKT_KLIJENT FOREIGN KEY (KUPAC_ID) 
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT CHK_KONTAKT_TIP CHECK (TIP_KONTAKTA IN ('TE', 'MO', 'EM', 'FA')),
    CONSTRAINT CHK_GLAVNI_KONTAKT CHECK (GLAVNI_KONTAKT IN ('D', 'N')),
    CONSTRAINT CHK_KONTAKT_STATUS CHECK (STATUS IN ('A', 'N'))
) IN BANKTEST.TSBANMAS;