-- KLIJENT ADRESE - NORMALIZIRANO
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE TABLE KLIJENT_ADRESE (
    ADRESA_ID           BIGINT          NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_ADRESE          CHAR(2)         NOT NULL,
    ULICA_BROJ          VARCHAR(100)    NOT NULL,
    GRAD                VARCHAR(30)     NOT NULL,
    POSTANSKI_BROJ      CHAR(5)         NOT NULL,
    DRZAVA              CHAR(2)         DEFAULT 'HR',
    GLAVNA_ADRESA       CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_OD            DATE            NOT NULL,
    DATUM_DO            DATE,
    
    CONSTRAINT PK_KLIJENT_ADRESE PRIMARY KEY (ADRESA_ID),
    CONSTRAINT FK_ADRESA_KLIJENT FOREIGN KEY (KUPAC_ID) 
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT CHK_ADRESA_TIP CHECK (TIP_ADRESE IN ('ST', 'PO', 'RA', 'PR')),
    CONSTRAINT CHK_GLAVNA_ADRESA CHECK (GLAVNA_ADRESA IN ('D', 'N')),
    CONSTRAINT CHK_ADRESA_STATUS CHECK (STATUS IN ('A', 'N')),
    CONSTRAINT CHK_ADRESA_DATUMI CHECK (DATUM_DO IS NULL OR DATUM_DO > DATUM_OD)
) IN BANKTEST.TSBANMAS;