-- GLAVNI KLIJENTI - SAMO OSNOVNI PODACI
CREATE TABLE KLIJENTI (
    KUPAC_ID            BIGINT          NOT NULL,
    OIB                 CHAR(11)        NOT NULL UNIQUE,
    IME                 VARCHAR(30)     NOT NULL,
    PREZIME             VARCHAR(30)     NOT NULL,
    DATUM_RODJENJA      DATE            NOT NULL,
    RIZIK_OCJENA        CHAR(2)         DEFAULT 'S1',
    STATUS              CHAR(1)         DEFAULT 'A',
    POSLOVNICA_KREIRANJE CHAR(4)        NOT NULL,
    DATUM_KREIRANJE     TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    ZADNJE_AZURIRANJE   TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    KREIRAO_USER        VARCHAR(10)     NOT NULL,
    
    CONSTRAINT PK_KLIJENTI PRIMARY KEY (KUPAC_ID),
    CONSTRAINT FK_KLIJENT_RIZIK FOREIGN KEY (RIZIK_OCJENA) 
        REFERENCES RIZIK_OCJENA_REF (RIZIK_KOD),
    CONSTRAINT FK_KLIJENT_POSLOVNICA FOREIGN KEY (POSLOVNICA_KREIRANJE) 
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_OIB_FORMAT CHECK (LENGTH(TRIM(OIB)) = 11),
    CONSTRAINT CHK_KUPAC_ID_RASPON CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);