-- RED TRANSAKCIJA
CREATE TABLE RED_TRANSAKCIJA (
    RED_ID              BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    KOD_TRANSAKCIJE     CHAR(4)         NOT NULL,
    IZNOS               DECIMAL(15,2)   NOT NULL,
    VRIJEME_ZAPRIMLJENO TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    DATUM_OBRADE        DATE            NOT NULL,
    IZVORNI_SUSTAV      CHAR(6)         NOT NULL,
    POZIV_NA_BROJ       VARCHAR(20),
    OPIS                VARCHAR(50),
    STATUS              CHAR(1)         DEFAULT 'C',
    PORUKA_GRESKE       VARCHAR(200),
    VRIJEME_OBRADE      TIMESTAMP,
    BROJ_PONOVNIH       SMALLINT        DEFAULT 0,
    POSLOVNICA_OBRADA   CHAR(4)         NOT NULL,
    
    CONSTRAINT PK_RED_TRANSAKCIJA PRIMARY KEY (RED_ID),
    CONSTRAINT FK_RED_RACUN FOREIGN KEY (RACUN_BROJ) 
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_RED_TIP FOREIGN KEY (KOD_TRANSAKCIJE) 
        REFERENCES TRANSAKCIJA_TIP_REF (TRN_TIP_KOD),
    CONSTRAINT FK_RED_SUSTAV FOREIGN KEY (IZVORNI_SUSTAV) 
        REFERENCES IZVORNI_SUSTAV_REF (SUSTAV_KOD),
    CONSTRAINT FK_RED_POSLOVNICA FOREIGN KEY (POSLOVNICA_OBRADA) 
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_RED_STATUS CHECK (STATUS IN ('C', 'U', 'N', 'P')),
    CONSTRAINT CHK_BROJ_PONOVNIH CHECK (BROJ_PONOVNIH >= 0 AND BROJ_PONOVNIH <= 5)
);