-- BLOKADE
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE TABLE BLOKADE (
    BLOKADA_ID          CHAR(15)        NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    TIP_BLOKADE         CHAR(3)         NOT NULL,
    IZNOS_BLOKADE       DECIMAL(15,2)   NOT NULL,
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    KOD_RAZLOGA         CHAR(4)         NOT NULL,
    STATUS              CHAR(1)         DEFAULT 'A',
    POSLOVNICA_KREIRANJE CHAR(4)        NOT NULL,
    KREIRAO             VARCHAR(10)     NOT NULL,
    VREMENSKI_KREIRANJE TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    OSLOBODIO           VARCHAR(10),
    VREMENSKI_OSLOBAJANJE TIMESTAMP,
    
    CONSTRAINT PK_BLOKADE PRIMARY KEY (BLOKADA_ID),
    CONSTRAINT FK_BLOKADA_RACUN FOREIGN KEY (RACUN_BROJ) 
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_BLOKADA_POSLOVNICA FOREIGN KEY (POSLOVNICA_KREIRANJE) 
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_BLOKADA_STATUS CHECK (STATUS IN ('A', 'O', 'I')),
    CONSTRAINT CHK_TIP_BLOKADE CHECK (TIP_BLOKADE IN ('CEK', 'PRA', 'SIG', 'KRE', 'NAP')),
    CONSTRAINT CHK_BLOKADA_DATUMI CHECK (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA >= DATUM_VAZENJA),
    CONSTRAINT CHK_IZNOS_BLOKADE CHECK (IZNOS_BLOKADE >= 0)
);