-- Glavne privilegije za aplikaciju (za sada IBMUSER)
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENTI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.RACUNI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.TRANSAKCIJE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.BLOKADE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.RED_TRANSAKCIJA TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.GLAVNA_KNJIGA TO IBMUSER, AGIBAS;

-- Privilegije na normalizirane tablice
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENT_ADRESE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENT_KONTAKTI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENT_DOKUMENTI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KAMATNE_STOPE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.RACUN_PROIZVODI TO IBMUSER, AGIBAS;

-- Privilegije na reference tablice
GRANT SELECT, INSERT, UPDATE ON BANKING_TEST.POSLOVNICE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE ON BANKING_TEST.PROIZVOD_MASTER TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.RIZIK_OCJENA_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.STATUS_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.TIP_RACUNA_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.TRANSAKCIJA_TIP_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.IZVORNI_SUSTAV_REF TO IBMUSER, AGIBAS;

-- Privilegije na sekvence
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_KUPAC_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_TRANSAKCIJA_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_BLOKADA_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_UNOS_GK_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_RED_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_ADRESA_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_KONTAKT_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_DOKUMENT_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_STOPA_ID TO IBMUSER, AGIBAS;