-- RACUN-PROIZVOD VEZA (M:N)
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE TABLE RACUN_PROIZVODI (
    RACUN_BROJ          CHAR(12)        NOT NULL,
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    DATUM_DODJELE       DATE            NOT NULL,
    DATUM_UKLANJANJA    DATE,
    STATUS              CHAR(1)         DEFAULT 'A',
    KREIRAO_USER        VARCHAR(10)     NOT NULL,
    
    CONSTRAINT PK_RACUN_PROIZVODI PRIMARY KEY (RACUN_BROJ, PROIZVOD_KOD),
    CONSTRAINT FK_RP_RACUN FOREIGN KEY (RACUN_BROJ) 
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_RP_PROIZVOD FOREIGN KEY (PROIZVOD_KOD) 
        REFERENCES PROIZVOD_MASTER (PROIZVOD_KOD),
    CONSTRAINT CHK_RP_STATUS CHECK (STATUS IN ('A', 'N')),
    CONSTRAINT CHK_RP_DATUMI CHECK (DATUM_UKLANJANJA IS NULL OR DATUM_UKLANJANJA > DATUM_DODJELE)
) IN BANKTEST.TSBANMAS;