-- RACUNI - SAMO RACUN PODACI
CREATE TABLE RACUNI (
    RACUN_BROJ          CHAR(12)        NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_RACUNA          CHAR(3)         NOT NULL,
    TRENUTNI_SALDO      DECIMAL(15,2)   DEFAULT 0.00,
    DOSTUPNI_SALDO      DECIMAL(15,2)   DEFAULT 0.00,
    KAMATA_STOPA        DECIMAL(5,4)    DEFAULT 0.0000,
    MINUS_LIMIT         DECIMAL(10,2)   DEFAULT 0.00,
    STATUS              CHAR(1)         DEFAULT 'A',
    POSLOVNICA_OTVARANJA CHAR(4)        NOT NULL,
    DATUM_OTVARANJA     DATE            NOT NULL,
    ZADNJA_AKTIVNOST    TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    DATUM_ZATVARANJA    DATE,
    KREIRAO_USER        VARCHAR(10)     NOT NULL,
    
    CONSTRAINT PK_RACUNI PRIMARY KEY (RACUN_BROJ),
    CONSTRAINT FK_RACUN_KLIJENT FOREIGN KEY (KUPAC_ID) 
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT FK_RACUN_TIP FOREIGN KEY (TIP_RACUNA) 
        REFERENCES TIP_RACUNA_REF (TIP_KOD),
    CONSTRAINT FK_RACUN_POSLOVNICA FOREIGN KEY (POSLOVNICA_OTVARANJA) 
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_RACUN_STATUS CHECK (STATUS IN ('A', 'Z', 'B', 'M')),
    CONSTRAINT CHK_SALDO_LOGIKA CHECK (DOSTUPNI_SALDO <= TRENUTNI_SALDO + MINUS_LIMIT)
);