SET CURRENT SCHEMA = 'BANKING_TEST';
-- KLIJENTI INDEKSI
CREATE INDEX IDX_KLIJENTI_OIB ON KLIJENTI (OIB);
CREATE INDEX IDX_KLIJENTI_RIZIK ON KLIJENTI (RIZIK_OCJENA);
CREATE INDEX IDX_KLIJENTI_STATUS ON KLIJENTI (STATUS);
CREATE INDEX IDX_KLIJENTI_POSLOVNICA ON KLIJENTI (POSLOVNICA_KREIRANJE);

-- RACUNI INDEKSI
CREATE INDEX IDX_RACUNI_KUPAC ON RACUNI (KUPAC_ID);
CREATE INDEX IDX_RACUNI_STATUS ON RACUNI (STATUS);
CREATE INDEX IDX_RACUNI_TIP ON RACUNI (TIP_RACUNA);
CREATE INDEX IDX_RACUNI_SALDO ON RACUNI (TRENUTNI_SALDO);
CREATE INDEX IDX_RACUNI_AKTIVNOST ON RACUNI (ZADNJA_AKTIVNOST);

-- TRANSAKCIJE INDEKSI
CREATE INDEX IDX_TRANSAKCIJE_RACUN ON TRANSAKCIJE (RACUN_BROJ);
CREATE INDEX IDX_TRANSAKCIJE_DATUM ON TRANSAKCIJE (DATUM_TRANSAKCIJE);
CREATE INDEX IDX_TRANSAKCIJE_KNJIZENJE ON TRANSAKCIJE (DATUM_KNJIZENJA);
CREATE INDEX IDX_TRANSAKCIJE_KOD ON TRANSAKCIJE (KOD_TRANSAKCIJE);
CREATE INDEX IDX_TRANSAKCIJE_STATUS ON TRANSAKCIJE (STATUS);
CREATE INDEX IDX_TRANSAKCIJE_IZVOR ON TRANSAKCIJE (IZVORNI_SUSTAV);

-- OSTALI INDEKSI
CREATE INDEX IDX_BLOKADE_RACUN ON BLOKADE (RACUN_BROJ);
CREATE INDEX IDX_BLOKADE_VAZENJE ON BLOKADE (DATUM_VAZENJA);
CREATE INDEX IDX_BLOKADE_STATUS ON BLOKADE (STATUS);
CREATE INDEX IDX_RED_RACUN ON RED_TRANSAKCIJA (RACUN_BROJ);
CREATE INDEX IDX_RED_STATUS ON RED_TRANSAKCIJA (STATUS);
CREATE INDEX IDX_GK_DATUM ON GLAVNA_KNJIGA (POSLOVNI_DATUM);
CREATE INDEX IDX_GK_RACUN ON GLAVNA_KNJIGA (RACUN_GK);