SET CURRENT SCHEMA = 'BANKING_TEST';
-- KLIJENTI INDEKSI
CREATE INDEX IDX_KLIJENTI_OIB ON KLIJENTI (OIB) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_KLIJENTI_RIZIK ON KLIJENTI (RIZIK_OCJENA) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_KLIJENTI_STATUS ON KLIJENTI (STATUS) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_KLIJENTI_POSLOVNICA ON KLIJENTI (POSLOVNICA_KREIRANJE) IN BANKTEST.TSBANTRS;

-- RACUNI INDEKSI
CREATE INDEX IDX_RACUNI_KUPAC ON RACUNI (KUPAC_ID) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_RACUNI_STATUS ON RACUNI (STATUS) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_RACUNI_TIP ON RACUNI (TIP_RACUNA) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_RACUNI_SALDO ON RACUNI (TRENUTNI_SALDO) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_RACUNI_AKTIVNOST ON RACUNI (ZADNJA_AKTIVNOST) IN BANKTEST.TSBANTRS;

-- TRANSAKCIJE INDEKSI
CREATE INDEX IDX_TRANSAKCIJE_RACUN ON TRANSAKCIJE (RACUN_BROJ) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_TRANSAKCIJE_DATUM ON TRANSAKCIJE (DATUM_TRANSAKCIJE) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_TRANSAKCIJE_KNJIZENJE ON TRANSAKCIJE (DATUM_KNJIZENJA) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_TRANSAKCIJE_KOD ON TRANSAKCIJE (KOD_TRANSAKCIJE) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_TRANSAKCIJE_STATUS ON TRANSAKCIJE (STATUS) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_TRANSAKCIJE_IZVOR ON TRANSAKCIJE (IZVORNI_SUSTAV) IN BANKTEST.TSBANTRS;

-- OSTALI INDEKSI
CREATE INDEX IDX_BLOKADE_RACUN ON BLOKADE (RACUN_BROJ) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_BLOKADE_VAZENJE ON BLOKADE (DATUM_VAZENJA) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_BLOKADE_STATUS ON BLOKADE (STATUS) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_RED_RACUN ON RED_TRANSAKCIJA (RACUN_BROJ) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_RED_STATUS ON RED_TRANSAKCIJA (STATUS) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_GK_DATUM ON GLAVNA_KNJIGA (POSLOVNI_DATUM) IN BANKTEST.TSBANTRS;
CREATE INDEX IDX_GK_RACUN ON GLAVNA_KNJIGA (RACUN_GK) IN BANKTEST.TSBANTRS;