-- KLIJENTI INDEKSI
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE UNIQUE INDEX UX_KLIJENTI_OIB 
    ON KLIJENTI (OIB) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

CREATE INDEX IDX_KLIJENTI_RIZIK 
    ON KLIJENTI (RIZIK_OCJENA) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

CREATE INDEX IDX_KLIJENTI_STATUS 
    ON KLIJENTI (STATUS) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

CREATE INDEX IDX_KLIJENTI_POSLOVNICA 
    ON KLIJENTI (POSLOVNICA_KREIRANJE) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

-- RACUNI INDEKSI
CREATE INDEX IDX_RACUNI_KUPAC 
    ON RACUNI (KUPAC_ID) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

CREATE INDEX IDX_RACUNI_STATUS 
    ON RACUNI (STATUS) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

CREATE INDEX IDX_RACUNI_TIP 
    ON RACUNI (TIP_RACUNA) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

CREATE INDEX IDX_RACUNI_SALDO 
    ON RACUNI (TRENUTNI_SALDO) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

CREATE INDEX IDX_RACUNI_AKTIVNOST 
    ON RACUNI (ZADNJA_AKTIVNOST) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

-- TRANSAKCIJE INDEKSI (Kritični za performanse)
CREATE INDEX IDX_TRANSAKCIJE_RACUN 
    ON TRANSAKCIJE (RACUN_BROJ) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 8M SECQTY 2M
    BUFFERPOOL BP0;

CREATE INDEX IDX_TRANSAKCIJE_DATUM 
    ON TRANSAKCIJE (DATUM_TRANSAKCIJE) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 4M SECQTY 1M
    BUFFERPOOL BP0;

CREATE INDEX IDX_TRANSAKCIJE_KNJIZENJE 
    ON TRANSAKCIJE (DATUM_KNJIZENJA) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 4M SECQTY 1M
    BUFFERPOOL BP0;

CREATE INDEX IDX_TRANSAKCIJE_KOD 
    ON TRANSAKCIJE (KOD_TRANSAKCIJE) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

CREATE INDEX IDX_TRANSAKCIJE_STATUS 
    ON TRANSAKCIJE (STATUS) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

CREATE INDEX IDX_TRANSAKCIJE_IZVOR 
    ON TRANSAKCIJE (IZVORNI_SUSTAV) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

-- Composite indeks za često korištene kombinacije
CREATE INDEX IDX_TRANSAKCIJE_RACUN_DATUM 
    ON TRANSAKCIJE (RACUN_BROJ, DATUM_TRANSAKCIJE DESC) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 8M SECQTY 2M
    BUFFERPOOL BP0;

-- BLOKADE INDEKSI
CREATE INDEX IDX_BLOKADE_RACUN 
    ON BLOKADE (RACUN_BROJ) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

CREATE INDEX IDX_BLOKADE_VAZENJE 
    ON BLOKADE (DATUM_VAZENJA) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

CREATE INDEX IDX_BLOKADE_STATUS 
    ON BLOKADE (STATUS) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

-- RED TRANSAKCIJA INDEKSI
CREATE INDEX IDX_RED_RACUN 
    ON RED_TRANSAKCIJA (RACUN_BROJ) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

CREATE INDEX IDX_RED_STATUS 
    ON RED_TRANSAKCIJA (STATUS) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 1M SECQTY 256K
    BUFFERPOOL BP0;

-- GLAVNA KNJIGA INDEKSI
CREATE INDEX IDX_GK_DATUM 
    ON GLAVNA_KNJIGA (POSLOVNI_DATUM) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;

CREATE INDEX IDX_GK_RACUN 
    ON GLAVNA_KNJIGA (RACUN_GK) 
    USING STOGROUP SYSDEFLT 
    PRIQTY 2M SECQTY 512K
    BUFFERPOOL BP0;