-- Reference tablice
CREATE TABLESPACE TSBANREF
    IN "BANKTEST"
    USING STOGROUP SYSDEFLT
    PRIQTY 8192
    SECQTY 2048
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CCSID UNICODE;

-- Master entiteti  
CREATE TABLESPACE TSBANMAS
    IN "BANKTEST"
    USING STOGROUP SYSDEFLT
    PRIQTY 16384
    SECQTY 4096
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CCSID UNICODE;

-- Transakcijski podaci
CREATE TABLESPACE TSBANTRS
    IN "BANKTEST"
    USING STOGROUP SYSDEFLT
    PRIQTY 32768
    SECQTY 8192
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CCSID UNICODE;

-- Indeksi
CREATE TABLESPACE TSBANIDX
    IN "BANKTEST"
    USING STOGROUP SYSDEFLT
    PRIQTY 8192
    SECQTY 2048
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CCSID UNICODE;