-- Reference tablice (manje podataka)
CREATE TABLESPACE TS_BANK_REF_TEST
    IN DATABASE BANKTEST
    USING STOGROUP SYSDEFLT
    PRIQTY 8M
    SECQTY 2M
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CCSID UNICODE;