-- Indeksi
CREATE TABLESPACE TS_BANK_IX_TEST
    IN DATABASE DSNDB04
    USING STOGROUP SYSDEFLT
    PRIQTY 16M
    SECQTY 4M
    ERASE NO
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CLOSE NO
    CCSID UNICODE;

COMMIT;