-- Transakcijski podaci (veliki volumen)
CREATE TABLESPACE TS_BANK_TRANS_TEST
    IN DATABASE DSNDB04
    USING STOGROUP SYSDEFLT
    PRIQTY 128M
    SECQTY 32M
    ERASE NO
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CLOSE NO
    CCSID UNICODE;