-- Reference tablice (manje podataka)
CREATE TABLESPACE TS_BANK_REF_TEST
    IN DATABASE DSNDB04
    USING STOGROUP SYSDEFLT
    PRIQTY 8M
    SECQTY 2M
    ERASE NO
    BUFFERPOOL BP0
    LOCKSIZE ROW
    CLOSE NO
    CCSID UNICODE;