-- ==================================================================================
-- BANKING SYSTEM - MASTER DEPLOYMENT SCRIPT
-- Platform:    IBM DB2 z/OS v13
-- Schema:      BANKING_TEST
-- Database:    BANKTEST
-- Version:     1.0
-- Date:        2026-05-03
--
-- This script contains ALL DDL needed to build the banking system from scratch
-- in correct dependency order. Run as a single batch (DSNTEP2/DSNTIAD) or
-- copy-paste sections into SPUFI for interactive execution.
--
-- Companion runbook: Db2/deploy/DEPLOYMENT_GUIDE.md
-- For per-file step-by-step execution, follow the runbook instead.
-- ==================================================================================


-- ==================================================================================
-- STEP 1: CREATE DATABASE
-- ==================================================================================

CREATE DATABASE BANKTEST
    BUFFERPOOL BP1
    INDEXBP    BP2
    STOGROUP   SYSDEFLT
    CCSID      UNICODE;

COMMIT;


-- ==================================================================================
-- STEP 2: SET SCHEMA CONTEXT
-- ==================================================================================

SET CURRENT SCHEMA = 'BANKING_TEST';


-- ==================================================================================
-- STEP 3: REFERENCE TABLES
-- ==================================================================================

-- 3.1 POSLOVNICE
CREATE TABLESPACE TSPOSLOV IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE POSLOVNICE (
    POSLOVNICA_KOD      CHAR(4)         NOT NULL,
    NAZIV_POSLOVNICE    VARCHAR(50)     NOT NULL,
    ADRESA              VARCHAR(100)    NOT NULL,
    GRAD                VARCHAR(30)     NOT NULL,
    POSTANSKI_BROJ      CHAR(5)         NOT NULL,
    TELEFON             VARCHAR(15),
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_OTVARANJA     DATE            NOT NULL,
    CONSTRAINT PK_POSLOVNICE PRIMARY KEY (POSLOVNICA_KOD),
    CONSTRAINT CHK_POSLOVNICA_STATUS CHECK (STATUS IN ('A', 'Z', 'S'))
) IN BANKTEST.TSPOSLOV;

-- 3.2 RIZIK_OCJENA_REF
CREATE TABLESPACE TSRIZIK IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE RIZIK_OCJENA_REF (
    RIZIK_KOD           CHAR(2)         NOT NULL,
    NAZIV_RIZIKA        VARCHAR(30)     NOT NULL,
    OPIS_RIZIKA         VARCHAR(100),
    FAKTOR_RIZIKA       DECIMAL(3,2)    DEFAULT 1.00,
    STATUS              CHAR(1)         DEFAULT 'A',
    CONSTRAINT PK_RIZIK_OCJENA PRIMARY KEY (RIZIK_KOD),
    CONSTRAINT CHK_RIZIK_STATUS CHECK (STATUS IN ('A', 'N'))
) IN BANKTEST.TSRIZIK;

-- 3.3 STATUS_REF
CREATE TABLESPACE TSSTATUS IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE STATUS_REF (
    STATUS_KOD          CHAR(1)         NOT NULL,
    NAZIV_STATUSA       VARCHAR(20)     NOT NULL,
    OPIS_STATUSA        VARCHAR(50),
    STATUS_KATEGORIJA   VARCHAR(20)     NOT NULL,
    CONSTRAINT PK_STATUS_REF PRIMARY KEY (STATUS_KOD, STATUS_KATEGORIJA)
) IN BANKTEST.TSSTATUS;

-- 3.4 TIP_RACUNA_REF
CREATE TABLESPACE TSTIPRAC IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE TIP_RACUNA_REF (
    TIP_KOD             CHAR(3)         NOT NULL,
    NAZIV_TIPA          VARCHAR(30)     NOT NULL,
    OPIS_TIPA           VARCHAR(100),
    KAMATA_NOSIVA       CHAR(1)         DEFAULT 'N',
    MINUS_DOZVOLJEN     CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    CONSTRAINT PK_TIP_RACUNA PRIMARY KEY (TIP_KOD),
    CONSTRAINT CHK_TIP_KAMATA CHECK (KAMATA_NOSIVA IN ('D', 'N')),
    CONSTRAINT CHK_TIP_MINUS CHECK (MINUS_DOZVOLJEN IN ('D', 'N')),
    CONSTRAINT CHK_TIP_STATUS CHECK (STATUS IN ('A', 'N'))
) IN BANKTEST.TSTIPRAC;

-- 3.5 TRANSAKCIJA_TIP_REF
CREATE TABLESPACE TSTIPTRN IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE TRANSAKCIJA_TIP_REF (
    TRN_TIP_KOD         CHAR(4)         NOT NULL,
    NAZIV_TIPA          VARCHAR(30)     NOT NULL,
    OPIS_TIPA           VARCHAR(100),
    SMJER_SALDA         CHAR(1)         NOT NULL,
    NAKNADA_PRIMJENJIVA CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    CONSTRAINT PK_TRANSAKCIJA_TIP PRIMARY KEY (TRN_TIP_KOD),
    CONSTRAINT CHK_TRN_SMJER CHECK (SMJER_SALDA IN ('+', '-', '=')),
    CONSTRAINT CHK_TRN_NAKNADA CHECK (NAKNADA_PRIMJENJIVA IN ('D', 'N')),
    CONSTRAINT CHK_TRN_STATUS CHECK (STATUS IN ('A', 'N'))
) IN BANKTEST.TSTIPTRN;

-- 3.6 IZVORNI_SUSTAV_REF
CREATE TABLESPACE TSIZVOR IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE IZVORNI_SUSTAV_REF (
    SUSTAV_KOD          CHAR(3)         NOT NULL,
    NAZIV_SUSTAVA       VARCHAR(30)     NOT NULL,
    OPIS_SUSTAVA        VARCHAR(100),
    SIGURNOSNA_RAZINA   SMALLINT        DEFAULT 1,
    STATUS              CHAR(1)         DEFAULT 'A',
    CONSTRAINT PK_IZVORNI_SUSTAV PRIMARY KEY (SUSTAV_KOD),
    CONSTRAINT CHK_SUSTAV_SIGURNOST CHECK (SIGURNOSNA_RAZINA BETWEEN 1 AND 5),
    CONSTRAINT CHK_SUSTAV_STATUS CHECK (STATUS IN ('A', 'N'))
) IN BANKTEST.TSIZVOR;

COMMIT;


-- ==================================================================================
-- STEP 4: MASTER ENTITIES
-- ==================================================================================

-- 4.1 KLIJENTI
CREATE TABLESPACE TSKLIENT IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE KLIJENTI (
    KUPAC_ID            BIGINT          NOT NULL,
    OIB                 CHAR(11)        NOT NULL UNIQUE,
    IME                 VARCHAR(30)     NOT NULL,
    PREZIME             VARCHAR(30)     NOT NULL,
    DATUM_RODJENJA      DATE            NOT NULL,
    RIZIK_OCJENA        CHAR(2)         DEFAULT 'S1',
    STATUS              CHAR(1)         DEFAULT 'A',
    POSLOVNICA_KREIRANJE CHAR(4)        NOT NULL,
    DATUM_KREIRANJE     TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    ZADNJE_AZURIRANJE   TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    KREIRAO_USER        VARCHAR(10)     NOT NULL,
    CONSTRAINT PK_KLIJENTI PRIMARY KEY (KUPAC_ID),
    CONSTRAINT FK_KLIJENT_RIZIK FOREIGN KEY (RIZIK_OCJENA)
        REFERENCES RIZIK_OCJENA_REF (RIZIK_KOD),
    CONSTRAINT FK_KLIJENT_POSLOVNICA FOREIGN KEY (POSLOVNICA_KREIRANJE)
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_OIB_FORMAT CHECK (LENGTH(TRIM(OIB)) = 11),
    CONSTRAINT CHK_KUPAC_ID_RASPON CHECK
        (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
) IN BANKTEST.TSKLIENT;

-- 4.2 PROIZVOD_MASTER
CREATE TABLESPACE TSPROIZV IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE PROIZVOD_MASTER (
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    NAZIV_PROIZVODA     VARCHAR(50)     NOT NULL,
    OPIS_PROIZVODA      VARCHAR(200),
    TIP_RACUNA          CHAR(3)         NOT NULL,
    OSNOVNA_KAMATA      DECIMAL(5,4)    DEFAULT 0.0000,
    MINIMALNI_SALDO     DECIMAL(10,2)   DEFAULT 0.00,
    MJESECNA_NAKNADA    DECIMAL(7,2)    DEFAULT 0.00,
    MINUS_NAKNADA       DECIMAL(7,2)    DEFAULT 0.00,
    LIMIT_TRANSAKCIJA   INTEGER         DEFAULT 999,
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    CONSTRAINT PK_PROIZVOD_MASTER PRIMARY KEY (PROIZVOD_KOD),
    CONSTRAINT FK_PROIZVOD_TIP FOREIGN KEY (TIP_RACUNA)
        REFERENCES TIP_RACUNA_REF (TIP_KOD),
    CONSTRAINT CHK_PROIZVOD_STATUS CHECK (STATUS IN ('A', 'N', 'B')),
    CONSTRAINT CHK_PROIZVOD_DATUMI CHECK
        (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA > DATUM_VAZENJA)
) IN BANKTEST.TSPROIZV;

COMMIT;


-- ==================================================================================
-- STEP 5: DEPENDENT ENTITIES
-- ==================================================================================

-- 5.1 RACUNI
CREATE TABLESPACE TSRACUNI IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE RACUNI (
    RACUN_BROJ          CHAR(12)        NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_RACUNA          CHAR(3)         NOT NULL,
    TRENUTNI_SALDO      DECIMAL(15,2)   DEFAULT 0.00,
    DOSTUPNI_SALDO      DECIMAL(15,2)   DEFAULT 0.00,
    KAMATA_STOPA        DECIMAL(5,4)    DEFAULT 0.0000,
    MINUS_LIMIT         DECIMAL(10,2)   DEFAULT 0.00,
    STATUS              CHAR(1)         DEFAULT 'A',
    POSLOVNICA_OTVARANJA CHAR(4)        NOT NULL,
    DATUM_OTVARANJA     DATE            NOT NULL,
    ZADNJA_AKTIVNOST    TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    DATUM_ZATVARANJA    DATE,
    KREIRAO_USER        VARCHAR(10)     NOT NULL,
    CONSTRAINT PK_RACUNI PRIMARY KEY (RACUN_BROJ),
    CONSTRAINT FK_RACUN_KLIJENT FOREIGN KEY (KUPAC_ID)
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT FK_RACUN_TIP FOREIGN KEY (TIP_RACUNA)
        REFERENCES TIP_RACUNA_REF (TIP_KOD),
    CONSTRAINT FK_RACUN_POSLOVNICA FOREIGN KEY (POSLOVNICA_OTVARANJA)
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_RACUN_STATUS CHECK (STATUS IN ('A', 'Z', 'B', 'M')),
    CONSTRAINT CHK_SALDO_LOGIKA CHECK
        (DOSTUPNI_SALDO <= TRENUTNI_SALDO + MINUS_LIMIT)
) IN BANKTEST.TSRACUNI;

-- 5.2 KLIJENT_ADRESE
CREATE TABLESPACE TSADRESE IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE KLIJENT_ADRESE (
    ADRESA_ID           BIGINT          NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_ADRESE          CHAR(2)         NOT NULL,
    ULICA_BROJ          VARCHAR(100)    NOT NULL,
    GRAD                VARCHAR(30)     NOT NULL,
    POSTANSKI_BROJ      CHAR(5)         NOT NULL,
    DRZAVA              CHAR(2)         DEFAULT 'HR',
    GLAVNA_ADRESA       CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_OD            DATE            NOT NULL,
    DATUM_DO            DATE,
    CONSTRAINT PK_KLIJENT_ADRESE PRIMARY KEY (ADRESA_ID),
    CONSTRAINT FK_ADRESA_KLIJENT FOREIGN KEY (KUPAC_ID)
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT CHK_ADRESA_TIP CHECK (TIP_ADRESE IN ('ST', 'PO', 'RA', 'PR')),
    CONSTRAINT CHK_GLAVNA_ADRESA CHECK (GLAVNA_ADRESA IN ('D', 'N')),
    CONSTRAINT CHK_ADRESA_STATUS CHECK (STATUS IN ('A', 'N')),
    CONSTRAINT CHK_ADRESA_DATUMI CHECK (DATUM_DO IS NULL OR DATUM_DO > DATUM_OD)
) IN BANKTEST.TSADRESE;

-- 5.3 KLIJENT_KONTAKTI
CREATE TABLESPACE TSKONTKT IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE KLIJENT_KONTAKTI (
    KONTAKT_ID          BIGINT          NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_KONTAKTA        CHAR(2)         NOT NULL,
    VRIJEDNOST_KONTAKTA VARCHAR(50)     NOT NULL,
    GLAVNI_KONTAKT      CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_OD            DATE            NOT NULL,
    DATUM_DO            DATE,
    CONSTRAINT PK_KLIJENT_KONTAKTI PRIMARY KEY (KONTAKT_ID),
    CONSTRAINT FK_KONTAKT_KLIJENT FOREIGN KEY (KUPAC_ID)
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT CHK_KONTAKT_TIP CHECK (TIP_KONTAKTA IN ('TE', 'MO', 'EM', 'FA')),
    CONSTRAINT CHK_GLAVNI_KONTAKT CHECK (GLAVNI_KONTAKT IN ('D', 'N')),
    CONSTRAINT CHK_KONTAKT_STATUS CHECK (STATUS IN ('A', 'N'))
) IN BANKTEST.TSKONTKT;

-- 5.4 KLIJENT_DOKUMENTI
CREATE TABLESPACE TSDOKUM IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE KLIJENT_DOKUMENTI (
    DOKUMENT_ID         BIGINT          NOT NULL,
    KUPAC_ID            BIGINT          NOT NULL,
    TIP_DOKUMENTA       CHAR(3)         NOT NULL,
    BROJ_DOKUMENTA      VARCHAR(20)     NOT NULL,
    IZDAVATELJ          VARCHAR(50),
    DATUM_IZDAVANJA     DATE,
    DATUM_ISTEKA        DATE,
    PUTANJA_DATOTEKE    VARCHAR(200),
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_UPLOAD        TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_KLIJENT_DOKUMENTI PRIMARY KEY (DOKUMENT_ID),
    CONSTRAINT FK_DOKUMENT_KLIJENT FOREIGN KEY (KUPAC_ID)
        REFERENCES KLIJENTI (KUPAC_ID),
    CONSTRAINT CHK_DOKUMENT_TIP CHECK (TIP_DOKUMENTA IN ('LK', 'PAS', 'VLZ', 'OST')),
    CONSTRAINT CHK_DOKUMENT_STATUS CHECK (STATUS IN ('A', 'N', 'I'))
) IN BANKTEST.TSDOKUM;

-- 5.5 KAMATNE_STOPE
CREATE TABLESPACE TSKAMATA IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE KAMATNE_STOPE (
    STOPA_ID            INTEGER         NOT NULL,
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    RAZINA_RAZREDA      SMALLINT        NOT NULL,
    SALDO_OD            DECIMAL(15,2)   NOT NULL,
    SALDO_DO            DECIMAL(15,2),
    KAMATA_STOPA        DECIMAL(5,4)    NOT NULL,
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    METODA_IZRACUNA     CHAR(3)         DEFAULT 'DAN',
    CONSTRAINT PK_KAMATNE_STOPE PRIMARY KEY (STOPA_ID),
    CONSTRAINT FK_KAMATA_PROIZVOD FOREIGN KEY (PROIZVOD_KOD)
        REFERENCES PROIZVOD_MASTER (PROIZVOD_KOD),
    CONSTRAINT CHK_METODA_KAMATA CHECK (METODA_IZRACUNA IN ('DAN', 'MJE', 'KVA', 'GOD')),
    CONSTRAINT CHK_RAZINA_RAZRED CHECK (RAZINA_RAZREDA > 0),
    CONSTRAINT CHK_SALDO_OPSEG CHECK (SALDO_DO IS NULL OR SALDO_DO > SALDO_OD),
    CONSTRAINT CHK_KAMATA_DATUMI CHECK
        (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA > DATUM_VAZENJA)
) IN BANKTEST.TSKAMATA;

-- 5.6 RACUN_PROIZVODI (M:N junction)
CREATE TABLESPACE TSRACPRO IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE RACUN_PROIZVODI (
    RACUN_BROJ          CHAR(12)        NOT NULL,
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    DATUM_DODJELE       DATE            NOT NULL,
    DATUM_UKLANJANJA    DATE,
    STATUS              CHAR(1)         DEFAULT 'A',
    KREIRAO_USER        VARCHAR(10)     NOT NULL,
    CONSTRAINT PK_RACUN_PROIZVODI PRIMARY KEY (RACUN_BROJ, PROIZVOD_KOD),
    CONSTRAINT FK_RP_RACUN FOREIGN KEY (RACUN_BROJ)
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_RP_PROIZVOD FOREIGN KEY (PROIZVOD_KOD)
        REFERENCES PROIZVOD_MASTER (PROIZVOD_KOD),
    CONSTRAINT CHK_RP_STATUS CHECK (STATUS IN ('A', 'N')),
    CONSTRAINT CHK_RP_DATUMI CHECK
        (DATUM_UKLANJANJA IS NULL OR DATUM_UKLANJANJA > DATUM_DODJELE)
) IN BANKTEST.TSRACPRO;

COMMIT;


-- ==================================================================================
-- STEP 6: TRANSACTION TABLES
-- ==================================================================================

-- 6.1 TRANSAKCIJE
CREATE TABLESPACE TSTRANS IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE TRANSAKCIJE (
    TRANSAKCIJA_ID      CHAR(20)        NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    KOD_TRANSAKCIJE     CHAR(4)         NOT NULL,
    IZNOS               DECIMAL(15,2)   NOT NULL,
    DATUM_TRANSAKCIJE   DATE            NOT NULL,
    DATUM_KNJIZENJA     DATE            NOT NULL,
    OPIS                VARCHAR(50),
    POZIV_NA_BROJ       VARCHAR(20),
    TEKUCI_SALDO        DECIMAL(15,2)   NOT NULL,
    IZVORNI_SUSTAV      CHAR(3)         NOT NULL,
    STATUS              CHAR(1)         DEFAULT 'K',
    POSLOVNICA_UNOS     CHAR(4)         NOT NULL,
    OPERATER_UNOS       VARCHAR(10)     NOT NULL,
    VREMENSKI_ZAPIS     TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_TRANSAKCIJE PRIMARY KEY (TRANSAKCIJA_ID),
    CONSTRAINT FK_TRN_RACUN FOREIGN KEY (RACUN_BROJ)
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_TRN_TIP FOREIGN KEY (KOD_TRANSAKCIJE)
        REFERENCES TRANSAKCIJA_TIP_REF (TRN_TIP_KOD),
    CONSTRAINT FK_TRN_SUSTAV FOREIGN KEY (IZVORNI_SUSTAV)
        REFERENCES IZVORNI_SUSTAV_REF (SUSTAV_KOD),
    CONSTRAINT FK_TRN_POSLOVNICA FOREIGN KEY (POSLOVNICA_UNOS)
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_TRN_STATUS CHECK (STATUS IN ('K', 'P', 'O', 'G'))
) IN BANKTEST.TSTRANS;

-- 6.2 BLOKADE
CREATE TABLESPACE TSBLOK IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE BLOKADE (
    BLOKADA_ID          CHAR(15)        NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    TIP_BLOKADE         CHAR(3)         NOT NULL,
    IZNOS_BLOKADE       DECIMAL(15,2)   NOT NULL,
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    KOD_RAZLOGA         CHAR(4)         NOT NULL,
    STATUS              CHAR(1)         DEFAULT 'A',
    POSLOVNICA_KREIRANJE CHAR(4)        NOT NULL,
    KREIRAO             VARCHAR(10)     NOT NULL,
    VREMENSKI_KREIRANJE TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    OSLOBODIO           VARCHAR(10),
    VREMENSKI_OSLOBAJANJE TIMESTAMP,
    CONSTRAINT PK_BLOKADE PRIMARY KEY (BLOKADA_ID),
    CONSTRAINT FK_BLOKADA_RACUN FOREIGN KEY (RACUN_BROJ)
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_BLOKADA_POSLOVNICA FOREIGN KEY (POSLOVNICA_KREIRANJE)
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_BLOKADA_STATUS CHECK (STATUS IN ('A', 'O', 'I')),
    CONSTRAINT CHK_TIP_BLOKADE CHECK (TIP_BLOKADE IN ('CEK', 'PRA', 'SIG', 'KRE', 'NAP')),
    CONSTRAINT CHK_BLOKADA_DATUMI CHECK
        (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA >= DATUM_VAZENJA),
    CONSTRAINT CHK_IZNOS_BLOKADE CHECK (IZNOS_BLOKADE >= 0)
) IN BANKTEST.TSBLOK;

-- 6.3 RED_TRANSAKCIJA
CREATE TABLESPACE TSRED IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE RED_TRANSAKCIJA (
    RED_ID              BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    KOD_TRANSAKCIJE     CHAR(4)         NOT NULL,
    IZNOS               DECIMAL(15,2)   NOT NULL,
    VRIJEME_ZAPRIMLJENO TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    DATUM_OBRADE        DATE            NOT NULL,
    IZVORNI_SUSTAV      CHAR(3)         NOT NULL,
    POZIV_NA_BROJ       VARCHAR(20),
    OPIS                VARCHAR(50),
    STATUS              CHAR(1)         DEFAULT 'C',
    PORUKA_GRESKE       VARCHAR(200),
    VRIJEME_OBRADE      TIMESTAMP,
    BROJ_PONOVNIH       SMALLINT        DEFAULT 0,
    POSLOVNICA_OBRADA   CHAR(4)         NOT NULL,
    CONSTRAINT PK_RED_TRANSAKCIJA PRIMARY KEY (RED_ID),
    CONSTRAINT FK_RED_RACUN FOREIGN KEY (RACUN_BROJ)
        REFERENCES RACUNI (RACUN_BROJ),
    CONSTRAINT FK_RED_TIP FOREIGN KEY (KOD_TRANSAKCIJE)
        REFERENCES TRANSAKCIJA_TIP_REF (TRN_TIP_KOD),
    CONSTRAINT FK_RED_SUSTAV FOREIGN KEY (IZVORNI_SUSTAV)
        REFERENCES IZVORNI_SUSTAV_REF (SUSTAV_KOD),
    CONSTRAINT FK_RED_POSLOVNICA FOREIGN KEY (POSLOVNICA_OBRADA)
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_RED_STATUS CHECK (STATUS IN ('C', 'U', 'N', 'P')),
    CONSTRAINT CHK_BROJ_PONOVNIH CHECK (BROJ_PONOVNIH >= 0 AND BROJ_PONOVNIH <= 5)
) IN BANKTEST.TSRED;

-- 6.4 GLAVNA_KNJIGA
CREATE TABLESPACE TSGLAVNA IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE GLAVNA_KNJIGA (
    UNOS_ID             BIGINT          NOT NULL,
    RACUN_GK            CHAR(10)        NOT NULL,
    POSLOVNI_DATUM      DATE            NOT NULL,
    DUGOVNA_STRANA      DECIMAL(18,2)   DEFAULT 0.00,
    POTRAZNA_STRANA     DECIMAL(18,2)   DEFAULT 0.00,
    BROJ_TRANSAKCIJA    INTEGER         DEFAULT 0,
    OPIS                VARCHAR(100),
    POSLOVNICA_UNOS     CHAR(4)         NOT NULL,
    OPERATER_UNOS       VARCHAR(10)     NOT NULL,
    VREMENSKI_KREIRANJE TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    CONSTRAINT PK_GLAVNA_KNJIGA PRIMARY KEY (UNOS_ID),
    CONSTRAINT FK_GK_POSLOVNICA FOREIGN KEY (POSLOVNICA_UNOS)
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_GK_IZNOSI CHECK (
        (DUGOVNA_STRANA > 0 AND POTRAZNA_STRANA = 0) OR
        (POTRAZNA_STRANA > 0 AND DUGOVNA_STRANA = 0)
    ),
    CONSTRAINT CHK_GK_BROJ CHECK (BROJ_TRANSAKCIJA >= 0)
) IN BANKTEST.TSGLAVNA;

COMMIT;


-- ==================================================================================
-- STEP 7: SEQUENCES
-- ==================================================================================

CREATE SEQUENCE SEQ_KUPAC_ID
    AS BIGINT START WITH 100000000000 INCREMENT BY 1
    MAXVALUE 999999999999 NO CYCLE CACHE 1000 ORDER;

CREATE SEQUENCE SEQ_TRANSAKCIJA_ID
    AS BIGINT START WITH 1000000000 INCREMENT BY 1
    NO CYCLE CACHE 500 ORDER;

CREATE SEQUENCE SEQ_BLOKADA_ID
    AS BIGINT START WITH 1000000 INCREMENT BY 1
    NO CYCLE CACHE 50 ORDER;

CREATE SEQUENCE SEQ_UNOS_GK_ID
    AS BIGINT START WITH 1 INCREMENT BY 1
    NO CYCLE CACHE 1000 ORDER;

CREATE SEQUENCE SEQ_RED_ID
    AS BIGINT START WITH 1 INCREMENT BY 1
    NO CYCLE CACHE 200 ORDER;

CREATE SEQUENCE SEQ_ADRESA_ID
    AS BIGINT START WITH 1 INCREMENT BY 1
    NO CYCLE CACHE 100 ORDER;

CREATE SEQUENCE SEQ_KONTAKT_ID
    AS BIGINT START WITH 1 INCREMENT BY 1
    NO CYCLE CACHE 100 ORDER;

CREATE SEQUENCE SEQ_DOKUMENT_ID
    AS BIGINT START WITH 1 INCREMENT BY 1
    NO CYCLE CACHE 50 ORDER;

CREATE SEQUENCE SEQ_STOPA_ID
    AS BIGINT START WITH 1 INCREMENT BY 1
    NO CYCLE CACHE 100 ORDER;

COMMIT;


-- ==================================================================================
-- STEP 8: INDEXES
-- ==================================================================================
-- Note: detailed indexes with PRIQTY/SECQTY/BUFFERPOOL clauses are in
--       Db2/create/indeksi/indeksi_optimizacija.sql
-- For brevity, this master script uses minimal index DDL. For production, run
-- indeksi_optimizacija.sql instead of this section.

-- KLIJENTI
CREATE UNIQUE INDEX UX_KLIJENTI_OIB ON KLIJENTI (OIB);
CREATE INDEX IDX_KLIJENTI_RIZIK ON KLIJENTI (RIZIK_OCJENA);
CREATE INDEX IDX_KLIJENTI_STATUS ON KLIJENTI (STATUS);
CREATE INDEX IDX_KLIJENTI_POSLOVNICA ON KLIJENTI (POSLOVNICA_KREIRANJE);

-- RACUNI
CREATE INDEX IDX_RACUNI_KUPAC ON RACUNI (KUPAC_ID);
CREATE INDEX IDX_RACUNI_STATUS ON RACUNI (STATUS);
CREATE INDEX IDX_RACUNI_TIP ON RACUNI (TIP_RACUNA);
CREATE INDEX IDX_RACUNI_SALDO ON RACUNI (TRENUTNI_SALDO);
CREATE INDEX IDX_RACUNI_AKTIVNOST ON RACUNI (ZADNJA_AKTIVNOST);

-- TRANSAKCIJE
CREATE INDEX IDX_TRANSAKCIJE_RACUN ON TRANSAKCIJE (RACUN_BROJ);
CREATE INDEX IDX_TRANSAKCIJE_DATUM ON TRANSAKCIJE (DATUM_TRANSAKCIJE);
CREATE INDEX IDX_TRANSAKCIJE_KNJIZENJE ON TRANSAKCIJE (DATUM_KNJIZENJA);
CREATE INDEX IDX_TRANSAKCIJE_KOD ON TRANSAKCIJE (KOD_TRANSAKCIJE);
CREATE INDEX IDX_TRANSAKCIJE_STATUS ON TRANSAKCIJE (STATUS);
CREATE INDEX IDX_TRANSAKCIJE_IZVOR ON TRANSAKCIJE (IZVORNI_SUSTAV);
CREATE INDEX IDX_TRANSAKCIJE_RACUN_DATUM ON TRANSAKCIJE (RACUN_BROJ, DATUM_TRANSAKCIJE DESC);

-- BLOKADE
CREATE INDEX IDX_BLOKADE_RACUN ON BLOKADE (RACUN_BROJ);
CREATE INDEX IDX_BLOKADE_VAZENJE ON BLOKADE (DATUM_VAZENJA);
CREATE INDEX IDX_BLOKADE_STATUS ON BLOKADE (STATUS);

-- RED_TRANSAKCIJA
CREATE INDEX IDX_RED_RACUN ON RED_TRANSAKCIJA (RACUN_BROJ);
CREATE INDEX IDX_RED_STATUS ON RED_TRANSAKCIJA (STATUS);

-- GLAVNA_KNJIGA
CREATE INDEX IDX_GK_DATUM ON GLAVNA_KNJIGA (POSLOVNI_DATUM);
CREATE INDEX IDX_GK_RACUN ON GLAVNA_KNJIGA (RACUN_GK);

COMMIT;


-- ==================================================================================
-- STEP 9: REFERENCE DATA INSERTS
-- ==================================================================================

-- 9.1 POSLOVNICE
INSERT INTO POSLOVNICE VALUES
    ('0001', 'Glavna poslovnica Zagreb', 'Ilica 1', 'Zagreb', '10000', '01-1234567', 'A', '2020-01-01');
INSERT INTO POSLOVNICE VALUES
    ('0002', 'Poslovnica Split', 'Riva 5', 'Split', '21000', '021-567890', 'A', '2020-01-01');
INSERT INTO POSLOVNICE VALUES
    ('0003', 'Poslovnica Rijeka', 'Korzo 10', 'Rijeka', '51000', '051-345678', 'A', '2020-01-01');

-- 9.2 RIZIK_OCJENA_REF
INSERT INTO RIZIK_OCJENA_REF VALUES
    ('N1', 'Nizak rizik - premium', 'Klijenti s izvrsnom kreditnom povijesti', 0.50, 'A');
INSERT INTO RIZIK_OCJENA_REF VALUES
    ('N2', 'Nizak rizik - standard', 'Klijenti s dobrom kreditnom povijesti', 0.75, 'A');
INSERT INTO RIZIK_OCJENA_REF VALUES
    ('S1', 'Srednji rizik - nadziran', 'Klijenti s osrednjom kreditnom povijesti', 1.00, 'A');
INSERT INTO RIZIK_OCJENA_REF VALUES
    ('S2', 'Srednji rizik - povecani', 'Klijenti s problematicnom kreditnom povijesti', 1.25, 'A');
INSERT INTO RIZIK_OCJENA_REF VALUES
    ('V1', 'Visok rizik - ogranicen', 'Klijenti s losim kreditnim rejtingom', 1.50, 'A');
INSERT INTO RIZIK_OCJENA_REF VALUES
    ('V2', 'Visok rizik - maksimalan', 'Klijenti s vrlo losim kreditnim rejtingom', 2.00, 'A');

-- 9.3 STATUS_REF
INSERT INTO STATUS_REF VALUES ('A', 'Aktivan', 'Entitet je aktivan i operativan', 'GENERAL');
INSERT INTO STATUS_REF VALUES ('N', 'Neaktivan', 'Entitet je neaktivan', 'GENERAL');
INSERT INTO STATUS_REF VALUES ('Z', 'Zatvoren', 'Entitet je zatvoren', 'GENERAL');
INSERT INTO STATUS_REF VALUES ('S', 'Suspendiran', 'Entitet je privremeno suspendiran', 'GENERAL');
INSERT INTO STATUS_REF VALUES ('B', 'Blokiran', 'Entitet je blokiran', 'GENERAL');
INSERT INTO STATUS_REF VALUES ('M', 'Odrzavanje', 'Entitet je u procesu odrzavanja', 'GENERAL');
INSERT INTO STATUS_REF VALUES ('K', 'Knjizen', 'Transakcija je uspjesno knjizena', 'TRANSAKCIJA');
INSERT INTO STATUS_REF VALUES ('P', 'Pending', 'Transakcija je na cekanju', 'TRANSAKCIJA');
INSERT INTO STATUS_REF VALUES ('O', 'Otkazana', 'Transakcija je otkazana', 'TRANSAKCIJA');
INSERT INTO STATUS_REF VALUES ('G', 'Greska', 'Greska u obradi transakcije', 'TRANSAKCIJA');
INSERT INTO STATUS_REF VALUES ('C', 'Ceka', 'U redu za obradu', 'QUEUE');
INSERT INTO STATUS_REF VALUES ('U', 'U obradi', 'Trenutno se obradjuje', 'QUEUE');
INSERT INTO STATUS_REF VALUES ('I', 'Istekla', 'Blokada je istekla', 'BLOKADA');

-- 9.4 TIP_RACUNA_REF
INSERT INTO TIP_RACUNA_REF VALUES
    ('TEK', 'Tekuci racun', 'Racun za svakodnevne transakcije', 'N', 'D', 'A');
INSERT INTO TIP_RACUNA_REF VALUES
    ('STD', 'Stedni racun', 'Racun za stednju s kamatom', 'D', 'N', 'A');
INSERT INTO TIP_RACUNA_REF VALUES
    ('ORO', 'Oroceni racun', 'Vezana stednja s visokom kamatom', 'D', 'N', 'A');
INSERT INTO TIP_RACUNA_REF VALUES
    ('KRE', 'Kreditni racun', 'Racun za kredite', 'N', 'D', 'A');
INSERT INTO TIP_RACUNA_REF VALUES
    ('KAR', 'Karticni racun', 'Racun vezan za kreditne kartice', 'N', 'D', 'A');

-- 9.5 TRANSAKCIJA_TIP_REF
INSERT INTO TRANSAKCIJA_TIP_REF VALUES
    ('UPL', 'Uplata gotovine', 'Uplata gotovine na racun', '+', 'N', 'A');
INSERT INTO TRANSAKCIJA_TIP_REF VALUES
    ('ISP', 'Isplata gotovine', 'Isplata gotovine s racuna', '-', 'D', 'A');
INSERT INTO TRANSAKCIJA_TIP_REF VALUES
    ('PRE', 'Prijenos sredstava', 'Prijenos izmedu racuna', '=', 'D', 'A');
INSERT INTO TRANSAKCIJA_TIP_REF VALUES
    ('NAK', 'Naknada', 'Banka naplacuje naknadu', '-', 'N', 'A');
INSERT INTO TRANSAKCIJA_TIP_REF VALUES
    ('KAM', 'Kamata', 'Kamata na racun', '+', 'N', 'A');
INSERT INTO TRANSAKCIJA_TIP_REF VALUES
    ('PRI', 'Primanje', 'Primanje iz vanjskih izvora', '+', 'N', 'A');
INSERT INTO TRANSAKCIJA_TIP_REF VALUES
    ('STO', 'Storno', 'Storno transakcije', '=', 'N', 'A');

-- 9.6 IZVORNI_SUSTAV_REF
INSERT INTO IZVORNI_SUSTAV_REF VALUES
    ('BAN', 'Bankar salter', 'Transakcija putem bankara na salteru', 5, 'A');
INSERT INTO IZVORNI_SUSTAV_REF VALUES
    ('SLU', 'Sluzba banke', 'Interna sluzba banke', 4, 'A');
INSERT INTO IZVORNI_SUSTAV_REF VALUES
    ('WEB', 'Web banking', 'Online bankarstvo', 3, 'A');
INSERT INTO IZVORNI_SUSTAV_REF VALUES
    ('ACH', 'ACH sustav', 'Automated Clearing House', 3, 'A');
INSERT INTO IZVORNI_SUSTAV_REF VALUES
    ('TEL', 'Telefonsko bankarstvo', 'Bankarstvo putem telefona', 2, 'A');
INSERT INTO IZVORNI_SUSTAV_REF VALUES
    ('LOT', 'Lutrija/ostalo', 'Ostali vanjski sustavi', 1, 'A');

-- 9.7 PROIZVOD_MASTER
INSERT INTO PROIZVOD_MASTER VALUES
    ('P001', 'Premium tekuci racun', 'Tekuci racun za premium klijente', 'TEK', 0.0000, 0.00, 0.00, 0.00, 999, 'A', '2020-01-01', NULL);
INSERT INTO PROIZVOD_MASTER VALUES
    ('P002', 'Standard tekuci racun', 'Standardni tekuci racun', 'TEK', 0.0000, 0.00, 15.00, 5.00, 100, 'A', '2020-01-01', NULL);
INSERT INTO PROIZVOD_MASTER VALUES
    ('P003', 'Mladenacka stednja', 'Stedni racun za mlade', 'STD', 1.5000, 100.00, 0.00, 0.00, 50, 'A', '2020-01-01', NULL);
INSERT INTO PROIZVOD_MASTER VALUES
    ('P004', 'Orocena stednja 12M', 'Orocena stednja na 12 mjeseci', 'ORO', 3.2500, 5000.00, 0.00, 0.00, 10, 'A', '2020-01-01', NULL);
INSERT INTO PROIZVOD_MASTER VALUES
    ('P005', 'Gotovinski kredit', 'Kratkorocni kredit', 'KRE', 8.5000, 0.00, 25.00, 0.00, 20, 'A', '2020-01-01', NULL);

-- 9.8 KAMATNE_STOPE
INSERT INTO KAMATNE_STOPE VALUES (1, 'P003', 1, 0.00, 10000.00, 1.5000, '2020-01-01', NULL, 'DAN');
INSERT INTO KAMATNE_STOPE VALUES (2, 'P003', 2, 10000.01, 50000.00, 2.0000, '2020-01-01', NULL, 'DAN');
INSERT INTO KAMATNE_STOPE VALUES (3, 'P003', 3, 50000.01, NULL, 2.5000, '2020-01-01', NULL, 'DAN');
INSERT INTO KAMATNE_STOPE VALUES (4, 'P004', 1, 5000.00, 100000.00, 3.2500, '2020-01-01', NULL, 'MJE');
INSERT INTO KAMATNE_STOPE VALUES (5, 'P004', 2, 100000.01, NULL, 3.7500, '2020-01-01', NULL, 'MJE');
INSERT INTO KAMATNE_STOPE VALUES (6, 'P005', 1, 0.00, NULL, 8.5000, '2020-01-01', NULL, 'DAN');

COMMIT;


-- ==================================================================================
-- STEP 10: TABLE COMMENTS (documentation)
-- ==================================================================================

COMMENT ON TABLE POSLOVNICE IS 'Organizacijska struktura - poslovnice banke';
COMMENT ON TABLE KLIJENTI IS 'Glavni podaci o klijentima - normalizirano';
COMMENT ON TABLE KLIJENT_ADRESE IS 'Adrese klijenta - vise adresa po klijentu';
COMMENT ON TABLE KLIJENT_KONTAKTI IS 'Kontakt podaci klijenta - telefoni, emailovi';
COMMENT ON TABLE KLIJENT_DOKUMENTI IS 'Dokumenti klijenta - sigurnosni podaci';
COMMENT ON TABLE PROIZVOD_MASTER IS 'Master katalog bankovnih proizvoda';
COMMENT ON TABLE KAMATNE_STOPE IS 'Kamatni razredi vezani za proizvode';
COMMENT ON TABLE RACUNI IS 'Racuni klijenata - ispravljena hijerarhija';
COMMENT ON TABLE RACUN_PROIZVODI IS 'Veza racun-proizvod (M:N relationship)';
COMMENT ON TABLE TRANSAKCIJE IS 'Transakcijska povijest - pojednostavljeno';
COMMENT ON TABLE BLOKADE IS 'Blokade racuna - bez redundantnih podataka';
COMMENT ON TABLE GLAVNA_KNJIGA IS 'Glavno knjizni unosi - bez klijent podataka';
COMMENT ON TABLE RED_TRANSAKCIJA IS 'Queue transakcija - pojednostavljeno';
COMMENT ON TABLE RIZIK_OCJENA_REF IS 'Reference tabela - rizik kategorije';
COMMENT ON TABLE STATUS_REF IS 'Reference tabela - statusni kodovi';
COMMENT ON TABLE TIP_RACUNA_REF IS 'Reference tabela - tipovi racuna';
COMMENT ON TABLE TRANSAKCIJA_TIP_REF IS 'Reference tabela - tipovi transakcija';
COMMENT ON TABLE IZVORNI_SUSTAV_REF IS 'Reference tabela - izvorni sustavi';

COMMIT;


-- ==================================================================================
-- STEP 11: GRANTS
-- ==================================================================================

GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENTI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.RACUNI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.TRANSAKCIJE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.BLOKADE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.RED_TRANSAKCIJA TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.GLAVNA_KNJIGA TO IBMUSER, AGIBAS;

GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENT_ADRESE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENT_KONTAKTI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KLIJENT_DOKUMENTI TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.KAMATNE_STOPE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE, DELETE ON BANKING_TEST.RACUN_PROIZVODI TO IBMUSER, AGIBAS;

GRANT SELECT, INSERT, UPDATE ON BANKING_TEST.POSLOVNICE TO IBMUSER, AGIBAS;
GRANT SELECT, INSERT, UPDATE ON BANKING_TEST.PROIZVOD_MASTER TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.RIZIK_OCJENA_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.STATUS_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.TIP_RACUNA_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.TRANSAKCIJA_TIP_REF TO IBMUSER, AGIBAS;
GRANT SELECT ON BANKING_TEST.IZVORNI_SUSTAV_REF TO IBMUSER, AGIBAS;

GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_KUPAC_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_TRANSAKCIJA_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_BLOKADA_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_UNOS_GK_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_RED_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_ADRESA_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_KONTAKT_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_DOKUMENT_ID TO IBMUSER, AGIBAS;
GRANT USAGE ON SEQUENCE BANKING_TEST.SEQ_STOPA_ID TO IBMUSER, AGIBAS;

COMMIT;


-- ==================================================================================
-- STEP 12: VALIDATION
-- ==================================================================================
-- Run Db2/schema/testovi/test_scheme.sql separately for full validation suite.
-- Quick smoke test:

SELECT 'TOTAL_TABLES' AS METRIC, COUNT(*) AS VALUE
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'BANKING_TEST' AND TYPE = 'T'
UNION ALL
SELECT 'TOTAL_INDEXES', COUNT(*)
FROM SYSIBM.SYSINDEXES WHERE CREATOR = 'BANKING_TEST'
UNION ALL
SELECT 'TOTAL_SEQUENCES', COUNT(*)
FROM SYSIBM.SYSSEQUENCES WHERE SCHEMA = 'BANKING_TEST'
UNION ALL
SELECT 'TOTAL_FK', COUNT(*)
FROM SYSIBM.SYSRELS WHERE CREATOR = 'BANKING_TEST';

-- Expected: 18 tables, 24+ indexes, 9 sequences, 24+ FK constraints

-- ==================================================================================
-- END OF DEPLOYMENT SCRIPT
-- ==================================================================================