-- =====================================================
-- DODJELJIVANJE DOZVOLA (PRILAGODITI PREMA VASEM OKRUŽENJU)
-- =====================================================
-- GRANT ALL ON KLIJENTI TO BANKOVNI_APP_ROLE;
-- GRANT ALL ON RACUNI TO BANKOVNI_APP_ROLE;
-- GRANT ALL ON PROIZVODI TO BANKOVNI_APP_ROLE;
-- GRANT ALL ON TRANSAKCIJE TO BANKOVNI_APP_ROLE;
-- GRANT ALL ON BLOKADE TO BANKOVNI_APP_ROLE;
-- GRANT ALL ON KAMATNE_STOPE TO BANKOVNI_APP_ROLE;
-- GRANT ALL ON GLAVNA_KNJIGA TO BANKOVNI_APP_ROLE;
-- GRANT ALL ON RED_TRANSAKCIJA TO BANKOVNI_APP_ROLE;

-- =====================================================
-- KOMENTARI TABLICA ZA DOKUMENTACIJU
-- =====================================================
COMMENT ON TABLE KLIJENTI IS 'GLAVNI PODACI O KLIJENTIMA SA STANDARDIZIRANIM KLJUCEVIMA - KUPAC_ID BIGINT(12)';
COMMENT ON TABLE RACUNI IS 'GLAVNI PODACI O RACUNIMA SA SALDIMA I STATUSOM';
COMMENT ON TABLE PROIZVODI IS 'KONFIGURACIJA PROIZVODA I DEFINICIJE ZNACAJKI';
COMMENT ON TABLE TRANSAKCIJE IS 'POTPUNA POVIJEST TRANSAKCIJA I REVIZIJSKI TRAG';
COMMENT ON TABLE BLOKADE IS 'BLOKADE RACUNA I OGRANICENJA SREDSTAVA';
COMMENT ON TABLE KAMATNE_STOPE IS 'KAMATNI RAZREDI I PARAMETRI IZRACUNA';
COMMENT ON TABLE GLAVNA_KNJIGA IS 'RACUNOVODSTVENI UNOSI I SAŽECI GK';
COMMENT ON TABLE RED_TRANSAKCIJA IS 'TRANSAKCIJE NA CEKANJU OBRADE';

-- =====================================================
-- KRAJ SKRIPTI ZA KREIRANJE TABLICA
-- =====================================================