-- =====================================================
-- KREIRANJE SEKVENCI ZA AUTOMATSKI GENERIRANE ID-JEVE
-- OPTIMIZIRANO ZA DB2 z/OS v13 S POBOLJSANIM CACHE STRATEGIJAMA
-- =====================================================

-- SEKVENCA ZA KUPAC_ID - 12 ZNAMENAKA (100 MILIJARDI - 999 MILIJARDI)
CREATE SEQUENCE SEQ_KUPAC_ID
   AS BIGINT
   START WITH 100000000000
   INCREMENT BY 1
   MAXVALUE 999999999999
   NO CYCLE
   CACHE 1000
   ORDER;

-- SEKVENCA ZA TRANSAKCIJA_ID - VISOKA FREKVENCIJA KORISTENJA  
CREATE SEQUENCE SEQ_TRANSAKCIJA_ID
   AS BIGINT
   START WITH 1000000000
   INCREMENT BY 1
   NO CYCLE
   CACHE 500
   ORDER;

-- SEKVENCA ZA BLOKADA_ID - NISKA FREKVENCIJA KORISTENJA
CREATE SEQUENCE SEQ_BLOKADA_ID
   AS BIGINT
   START WITH 1000000
   INCREMENT BY 1
   NO CYCLE
   CACHE 50
   ORDER;

-- SEKVENCA ZA GLAVNA_KNJIGA - VISOKA FREKVENCIJA KNJIZENJA
CREATE SEQUENCE SEQ_UNOS_GK_ID
   AS BIGINT
   START WITH 1
   INCREMENT BY 1
   NO CYCLE
   CACHE 1000
   ORDER;

-- SEKVENCA ZA RED_TRANSAKCIJA - UMJERENA FREKVENCIJA QUEUE OBRADE
CREATE SEQUENCE SEQ_RED_ID
   AS BIGINT
   START WITH 1
   INCREMENT BY 1
   NO CYCLE
   CACHE 200
   ORDER;