-- ==================================================================================
-- BANKING SYSTEM - DEPLOYMENT VALIDATION
-- Environment: TEST
-- Platform: IBM DB2 z/OS v13
-- ==================================================================================

SET CURRENT SCHEMA = 'BANKING_TEST';

-- ==================================================================================
-- CHECK 1: TABLE EXISTENCE
-- ==================================================================================

SELECT 'REFERENCE TABLES' AS KATEGORIJA, COUNT(*) AS BROJ_TABLICA
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'BANKING_TEST'
AND NAME IN ('POSLOVNICE', 'RIZIK_OCJENA_REF', 'STATUS_REF',
             'TIP_RACUNA_REF', 'TRANSAKCIJA_TIP_REF', 'IZVORNI_SUSTAV_REF')

UNION ALL

SELECT 'MASTER ENTITIES', COUNT(*)
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'BANKING_TEST'
AND NAME IN ('KLIJENTI', 'PROIZVOD_MASTER', 'RACUNI')

UNION ALL

SELECT 'NORMALIZED TABLES', COUNT(*)
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'BANKING_TEST'
AND NAME IN ('KLIJENT_ADRESE', 'KLIJENT_KONTAKTI', 'KLIJENT_DOKUMENTI',
             'KAMATNE_STOPE', 'RACUN_PROIZVODI')

UNION ALL

SELECT 'TRANSACTION TABLES', COUNT(*)
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'BANKING_TEST'
AND NAME IN ('TRANSAKCIJE', 'BLOKADE', 'RED_TRANSAKCIJA', 'GLAVNA_KNJIGA')

UNION ALL

SELECT 'TOTAL TABLES', COUNT(*)
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'BANKING_TEST'
AND TYPE = 'T';

-- ==================================================================================
-- CHECK 2: ROW COUNTS IN REFERENCE TABLES
-- ==================================================================================

SELECT 'POSLOVNICE' AS TABLICA, COUNT(*) AS BROJ_ZAPISA FROM POSLOVNICE
UNION ALL
SELECT 'RIZIK_OCJENA_REF', COUNT(*) FROM RIZIK_OCJENA_REF
UNION ALL
SELECT 'STATUS_REF', COUNT(*) FROM STATUS_REF
UNION ALL
SELECT 'TIP_RACUNA_REF', COUNT(*) FROM TIP_RACUNA_REF
UNION ALL
SELECT 'TRANSAKCIJA_TIP_REF', COUNT(*) FROM TRANSAKCIJA_TIP_REF
UNION ALL
SELECT 'IZVORNI_SUSTAV_REF', COUNT(*) FROM IZVORNI_SUSTAV_REF
UNION ALL
SELECT 'PROIZVOD_MASTER', COUNT(*) FROM PROIZVOD_MASTER
UNION ALL
SELECT 'KAMATNE_STOPE', COUNT(*) FROM KAMATNE_STOPE
ORDER BY TABLICA;

-- ==================================================================================
-- CHECK 3: INDEX COUNT
-- ==================================================================================

SELECT 'TOTAL INDEXES' AS TIP, COUNT(*) AS BROJ
FROM SYSIBM.SYSINDEXES
WHERE CREATOR = 'BANKING_TEST'

UNION ALL

SELECT 'UNIQUE INDEXES', COUNT(*)
FROM SYSIBM.SYSINDEXES
WHERE CREATOR = 'BANKING_TEST'
AND UNIQUERULE IN ('U', 'P')

UNION ALL

SELECT 'NON-UNIQUE INDEXES', COUNT(*)
FROM SYSIBM.SYSINDEXES
WHERE CREATOR = 'BANKING_TEST'
AND UNIQUERULE NOT IN ('U', 'P');

-- ==================================================================================
-- CHECK 4: SEQUENCE COUNT AND DETAILS
-- ==================================================================================

SELECT 'TOTAL SEQUENCES' AS TIP, COUNT(*) AS BROJ
FROM SYSIBM.SYSSEQUENCES
WHERE SCHEMA = 'BANKING_TEST';

SELECT NAME AS SEKVENCA,
       START AS POCETNA_VRIJEDNOST,
       INCREMENT AS KORAK
FROM SYSIBM.SYSSEQUENCES
WHERE SCHEMA = 'BANKING_TEST'
ORDER BY NAME;

-- ==================================================================================
-- CHECK 5: FOREIGN KEY CONSTRAINTS
-- ==================================================================================

SELECT 'TOTAL FK CONSTRAINTS' AS TIP, COUNT(*) AS BROJ
FROM SYSIBM.SYSRELS
WHERE CREATOR = 'BANKING_TEST';

SELECT TBNAME AS CHILD_TABLICA,
       REFTBNAME AS PARENT_TABLICA,
       RELNAME AS FK_NAME
FROM SYSIBM.SYSRELS
WHERE CREATOR = 'BANKING_TEST'
ORDER BY TBNAME, REFTBNAME;

-- ==================================================================================
-- CHECK 6: CHECK CONSTRAINTS
-- ==================================================================================

SELECT 'TOTAL CHECK CONSTRAINTS' AS TIP, COUNT(*) AS BROJ
FROM SYSIBM.SYSCHECKS
WHERE CREATOR = 'BANKING_TEST';

-- ==================================================================================
-- CHECK 7: TABLESPACE USAGE
-- ==================================================================================

SELECT TSNAME AS TABLESPACE_NAME, COUNT(*) AS BROJ_TABLICA
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'BANKING_TEST'
AND TSNAME IS NOT NULL
AND TYPE = 'T'
GROUP BY TSNAME
ORDER BY TSNAME;

-- ==================================================================================
-- CHECK 8: INSERT REFERENTIAL INTEGRITY TESTS
-- ==================================================================================

-- Test 1: Insert a test client
INSERT INTO KLIJENTI (
    KUPAC_ID, OIB, IME, PREZIME, DATUM_RODJENJA,
    RIZIK_OCJENA, POSLOVNICA_KREIRANJE, KREIRAO_USER
) VALUES (
    NEXT VALUE FOR SEQ_KUPAC_ID,
    '12345678901',
    'Test',
    'Klijent',
    '1990-01-01',
    'S1',
    '0001',
    'IBMUSER'
);

-- Test 2: Insert a test account
INSERT INTO RACUNI (
    RACUN_BROJ, KUPAC_ID, TIP_RACUNA, TRENUTNI_SALDO,
    DOSTUPNI_SALDO, POSLOVNICA_OTVARANJA, DATUM_OTVARANJA, KREIRAO_USER
) VALUES (
    '100000000001',
    (SELECT KUPAC_ID FROM KLIJENTI WHERE OIB = '12345678901'),
    'TEK',
    1000.00,
    1000.00,
    '0001',
    CURRENT DATE,
    'IBMUSER'
);

-- Test 3: Insert a test transaction
INSERT INTO TRANSAKCIJE (
    TRANSAKCIJA_ID, RACUN_BROJ, KOD_TRANSAKCIJE, IZNOS,
    DATUM_TRANSAKCIJE, DATUM_KNJIZENJA, OPIS, TEKUCI_SALDO,
    IZVORNI_SUSTAV, POSLOVNICA_UNOS, OPERATER_UNOS
) VALUES (
    '20260503000000000001',
    '100000000001',
    'UPL',
    1000.00,
    CURRENT DATE,
    CURRENT DATE,
    'Test uplata',
    1000.00,
    'BAN',
    '0001',
    'IBMUSER'
);

COMMIT;

-- ==================================================================================
-- CHECK 9: FINAL VALIDATION
-- ==================================================================================

SELECT 'TEST KLIJENTI' AS TIP, COUNT(*) AS BROJ
FROM KLIJENTI WHERE OIB = '12345678901'

UNION ALL

SELECT 'TEST RACUNI', COUNT(*)
FROM RACUNI WHERE RACUN_BROJ = '100000000001'

UNION ALL

SELECT 'TEST TRANSAKCIJE', COUNT(*)
FROM TRANSAKCIJE WHERE RACUN_BROJ = '100000000001';

SELECT
    K.IME CONCAT ' ' CONCAT K.PREZIME AS KLIJENT,
    R.RACUN_BROJ,
    R.TRENUTNI_SALDO,
    T.IZNOS AS ZADNJA_TRANSAKCIJA,
    P.NAZIV_POSLOVNICE
FROM KLIJENTI K
JOIN RACUNI R ON K.KUPAC_ID = R.KUPAC_ID
JOIN TRANSAKCIJE T ON R.RACUN_BROJ = T.RACUN_BROJ
JOIN POSLOVNICE P ON R.POSLOVNICA_OTVARANJA = P.POSLOVNICA_KOD
WHERE K.OIB = '12345678901';
