-- GLAVNA KNJIGA - BEZ KLIJENT PODATAKA
CREATE TABLE GLAVNA_KNJIGA (
    UNOS_ID             BIGINT          NOT NULL,
    RACUN_GK            CHAR(10)        NOT NULL,
    POSLOVNI_DATUM      DATE            NOT NULL,
    DUGOVNA_STRANA      DECIMAL(18,2)   DEFAULT 0.00,
    POTRAZNA_STRANA     DECIMAL(18,2)   DEFAULT 0.00,
    BROJ_TRANSAKCIJA    INTEGER         DEFAULT 0,
    OPIS                VARCHAR(100),
    POSLOVNICA_UNOS     CHAR(4)         NOT NULL,
    OPERATER_UNOS       VARCHAR(10)     NOT NULL,
    VREMENSKI_KREIRANJE TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    
    CONSTRAINT PK_GLAVNA_KNJIGA PRIMARY KEY (UNOS_ID),
    CONSTRAINT FK_GK_POSLOVNICA FOREIGN KEY (POSLOVNICA_UNOS) 
        REFERENCES POSLOVNICE (POSLOVNICA_KOD),
    CONSTRAINT CHK_GK_IZNOSI CHECK (
        (DUGOVNA_STRANA > 0 AND POTRAZNA_STRANA = 0) OR 
        (POTRAZNA_STRANA > 0 AND DUGOVNA_STRANA = 0)
    ),
    CONSTRAINT CHK_GK_BROJ CHECK (BROJ_TRANSAKCIJA >= 0)
);