-- =====================================================
-- BLOKADE TABLICA - BLOKADE I OGRANICENJA RACUNA
-- =====================================================
CREATE TABLE BLOKADE (
    KUPAC_ID            BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    BLOKADA_ID          CHAR(15)        NOT NULL,
    TIP_BLOKADE         CHAR(3)         NOT NULL,
    IZNOS_BLOKADE       DECIMAL(15,2)   NOT NULL,
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    KOD_RAZLOGA         CHAR(4)         NOT NULL,
    STATUS              CHAR(1)         DEFAULT 'A',
    KREIRAO             VARCHAR(10)     NOT NULL,
    VREMENSKI_KREIRANJE TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    OSLOBODIO           VARCHAR(10),
    VREMENSKI_OSLOBAJANJE TIMESTAMP,
    
    -- PRIMARNI I SEKUNDARNI KLJUCEVI
    CONSTRAINT PK_BLOKADE PRIMARY KEY (KUPAC_ID, RACUN_BROJ, BLOKADA_ID),
    
    -- STRANI KLJUC NA RACUNI
    CONSTRAINT FK_BLOKADE_RACUN FOREIGN KEY (KUPAC_ID, RACUN_BROJ) 
        REFERENCES RACUNI (KUPAC_ID, RACUN_BROJ),
    
    -- PROVJERE OGRANICENJA
    CONSTRAINT CHK_BLOKADA_STATUS CHECK (STATUS IN ('A', 'O', 'I')),
    CONSTRAINT CHK_TIP_BLOKADE CHECK (TIP_BLOKADE IN ('CEK', 'PRA', 'SIG', 'KRE', 'NAP')),
    CONSTRAINT CHK_BLOKADA_DATUMI CHECK (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA >= DATUM_VAZENJA),
    CONSTRAINT CHK_IZNOS_BLOKADE CHECK (IZNOS_BLOKADE >= 0),
    CONSTRAINT CHK_KUPAC_ID_BLOKADE CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);

-- KREIRANJE INDEKSA ZA BLOKADE
CREATE INDEX IDX_BLOKADE_VAZENJE ON BLOKADE (DATUM_VAZENJA);
CREATE INDEX IDX_BLOKADE_ISTEK ON BLOKADE (DATUM_ISTEKA);
CREATE INDEX IDX_BLOKADE_STATUS ON BLOKADE (STATUS);
CREATE INDEX IDX_BLOKADE_TIP ON BLOKADE (TIP_BLOKADE);