-- =====================================================
-- KAMATNE_STOPE TABLICA - KAMATNI RAZREDI
-- =====================================================
CREATE TABLE KAMATNE_STOPE (
    KUPAC_ID            BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    STOPA_ID            INTEGER         NOT NULL,
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    RAZINA_RAZREDA      SMALLINT        NOT NULL,
    SALDO_OD            DECIMAL(15,2)   NOT NULL,
    SALDO_DO            DECIMAL(15,2),
    KAMATA_STOPA        DECIMAL(5,4)    NOT NULL,
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    METODA_IZRACUNA     CHAR(3)         DEFAULT 'DAN',
    
    -- PRIMARNI I SEKUNDARNI KLJUCEVI
    CONSTRAINT PK_KAMATNE_STOPE PRIMARY KEY (KUPAC_ID, RACUN_BROJ, STOPA_ID),
    
    -- STRANI KLJUC NA PROIZVODI
    CONSTRAINT FK_KAMATA_PROIZVODI FOREIGN KEY (KUPAC_ID, RACUN_BROJ, PROIZVOD_KOD) 
        REFERENCES PROIZVODI (KUPAC_ID, RACUN_BROJ, PROIZVOD_KOD),
    
    -- PROVJERE OGRANICENJA
    CONSTRAINT CHK_METODA_KAMATA CHECK (METODA_IZRACUNA IN ('DAN', 'MJE', 'KVA', 'GOD')),
    CONSTRAINT CHK_RAZINA_RAZRED CHECK (RAZINA_RAZREDA > 0),
    CONSTRAINT CHK_SALDO_OPSEG CHECK (SALDO_DO IS NULL OR SALDO_DO > SALDO_OD),
    CONSTRAINT CHK_KAMATA_DATUMI CHECK (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA > DATUM_VAZENJA),
    CONSTRAINT CHK_KUPAC_ID_KAMATA CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);

-- KREIRANJE INDEKSA ZA KAMATNE_STOPE
CREATE INDEX IDX_KAMATA_VAZENJE ON KAMATNE_STOPE (DATUM_VAZENJA);
CREATE INDEX IDX_KAMATA_PROIZVOD ON KAMATNE_STOPE (PROIZVOD_KOD);
CREATE INDEX IDX_KAMATA_RAZRED ON KAMATNE_STOPE (RAZINA_RAZREDA);