-- =====================================================
-- KLIJENTI TABLICA - GLAVNI PODACI O KLIJENTIMA
-- =====================================================
CREATE TABLE KLIJENTI (
    KUPAC_ID            BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    OIB                 CHAR(11)        NOT NULL,
    IME                 VARCHAR(30)     NOT NULL,
    PREZIME             VARCHAR(30)     NOT NULL,
    ADRESA              VARCHAR(100)    NOT NULL,
    TELEFON             VARCHAR(15),
    DATUM_RODJENJA      DATE            NOT NULL,
    RIZIK_OCJENA        CHAR(2)         DEFAULT 'M1',
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_KREIRANJE     TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    ZADNJE_AZURIRANJE   TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    
    -- PRIMARNI I SEKUNDARNI KLJUCEVI
    CONSTRAINT PK_KLIJENTI PRIMARY KEY (KUPAC_ID, RACUN_BROJ),
    
    -- PROVJERE OGRANICENJA
    CONSTRAINT CHK_KLIJENT_STATUS CHECK (STATUS IN ('A', 'N', 'Z', 'S')),
    CONSTRAINT CHK_RIZIK_OCJENA CHECK (RIZIK_OCJENA IN ('N1', 'N2', 'S1', 'S2', 'V1', 'V2')),
    CONSTRAINT CHK_OIB_FORMAT CHECK (LENGTH(TRIM(OIB)) = 11),
    CONSTRAINT CHK_KUPAC_ID_LENGTH CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);

-- KREIRANJE INDEKSA ZA KLIJENTI
CREATE INDEX IDX_KLIJENTI_OIB ON KLIJENTI (OIB);
CREATE INDEX IDX_KLIJENTI_RIZIK ON KLIJENTI (RIZIK_OCJENA);
CREATE INDEX IDX_KLIJENTI_STATUS ON KLIJENTI (STATUS);