-- =====================================================
-- PROIZVODI TABLICA - KONFIGURACIJA PROIZVODA
-- =====================================================
CREATE TABLE PROIZVODI (
    KUPAC_ID            BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    NAZIV_PROIZVODA     VARCHAR(50)     NOT NULL,
    TIP_RACUNA          CHAR(3)         NOT NULL,
    OSNOVNA_KAMATA      DECIMAL(5,4)    DEFAULT 0.0000,
    MINIMALNI_SALDO     DECIMAL(10,2)   DEFAULT 0.00,
    MJESECNA_NAKNADA    DECIMAL(7,2)    DEFAULT 0.00,
    MINUS_NAKNADA       DECIMAL(7,2)    DEFAULT 0.00,
    LIMIT_TRANSAKCIJA   INTEGER         DEFAULT 999,
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_VAZENJA       DATE            NOT NULL,
    DATUM_ISTEKA        DATE,
    
    -- PRIMARNI I SEKUNDARNI KLJUCEVI
    CONSTRAINT PK_PROIZVODI PRIMARY KEY (KUPAC_ID, RACUN_BROJ, PROIZVOD_KOD),
    
    -- PROVJERE OGRANICENJA
    CONSTRAINT CHK_PROIZVOD_STATUS CHECK (STATUS IN ('A', 'N', 'B')),
    CONSTRAINT CHK_PROIZVOD_TIP CHECK (TIP_RACUNA IN ('TEK', 'STD', 'ORO', 'KRE', 'KAR')),
    CONSTRAINT CHK_PROIZVOD_DATUMI CHECK (DATUM_ISTEKA IS NULL OR DATUM_ISTEKA > DATUM_VAZENJA),
    CONSTRAINT CHK_KUPAC_ID_PROIZVODI CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);

-- KREIRANJE INDEKSA ZA PROIZVODI
CREATE INDEX IDX_PROIZVODI_TIP ON PROIZVODI (TIP_RACUNA);
CREATE INDEX IDX_PROIZVODI_STATUS ON PROIZVODI (STATUS);
CREATE INDEX IDX_PROIZVODI_VAZENJE ON PROIZVODI (DATUM_VAZENJA);