-- =====================================================
-- RACUNI TABLICA - GLAVNI PODACI O RACUNIMA
-- =====================================================
CREATE TABLE RACUNI (
    KUPAC_ID            BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    PROIZVOD_KOD        CHAR(4)         NOT NULL,
    TIP_RACUNA          CHAR(3)         NOT NULL,
    TRENUTNI_SALDO      DECIMAL(15,2)   DEFAULT 0.00,
    DOSTUPNI_SALDO      DECIMAL(15,2)   DEFAULT 0.00,
    KAMATA_STOPA        DECIMAL(5,4)    DEFAULT 0.0000,
    MINUS_LIMIT         DECIMAL(10,2)   DEFAULT 0.00,
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_OTVARANJA     DATE            NOT NULL,
    ZADNJA_AKTIVNOST    TIMESTAMP       NOT NULL WITH DEFAULT CURRENT TIMESTAMP,
    DATUM_ZATVARANJA    DATE,
    
    -- PRIMARNI I SEKUNDARNI KLJUCEVI
    CONSTRAINT PK_RACUNI PRIMARY KEY (KUPAC_ID, RACUN_BROJ),
    
    -- STRANI KLJUC NA KLIJENTI
    CONSTRAINT FK_RACUNI_KLIJENT FOREIGN KEY (KUPAC_ID) 
        REFERENCES KLIJENTI (KUPAC_ID),
    
    -- PROVJERE OGRANICENJA
    CONSTRAINT CHK_RACUN_STATUS CHECK (STATUS IN ('A', 'Z', 'B', 'M')),
    CONSTRAINT CHK_TIP_RACUNA CHECK (TIP_RACUNA IN ('TEK', 'STD', 'ORO', 'KRE', 'KAR')),
    CONSTRAINT CHK_SALDO_LOGIKA CHECK (DOSTUPNI_SALDO <= TRENUTNI_SALDO + MINUS_LIMIT),
    CONSTRAINT CHK_KUPAC_ID_RACUNI CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);

-- KREIRANJE INDEKSA ZA RACUNI
CREATE INDEX IDX_RACUNI_STATUS ON RACUNI (STATUS);
CREATE INDEX IDX_RACUNI_TIP ON RACUNI (TIP_RACUNA);
CREATE INDEX IDX_RACUNI_PROIZVOD ON RACUNI (PROIZVOD_KOD);
CREATE INDEX IDX_RACUNI_SALDO ON RACUNI (TRENUTNI_SALDO);