-- =====================================================
-- RED_TRANSAKCIJA TABLICA - CEKANJE TRANSAKCIJA
-- =====================================================
CREATE TABLE RED_TRANSAKCIJA (
    KUPAC_ID            BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    RED_ID              BIGINT          NOT NULL,
    KOD_TRANSAKCIJE     CHAR(4)         NOT NULL,
    IZNOS               DECIMAL(15,2)   NOT NULL,
    VRIJEME_ZAPRIMLJENO TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    DATUM_OBRADE        DATE            NOT NULL,
    IZVORNI_SUSTAV      CHAR(6)         NOT NULL,
    POZIV_NA_BROJ       VARCHAR(20),
    OPIS                VARCHAR(50),
    STATUS              CHAR(1)         DEFAULT 'C',
    PORUKA_GRESKE       VARCHAR(200),
    VRIJEME_OBRADE      TIMESTAMP,
    BROJ_PONOVNIH       SMALLINT        DEFAULT 0,
    
    -- PRIMARNI I SEKUNDARNI KLJUCEVI
    CONSTRAINT PK_RED_TRANSAKCIJA PRIMARY KEY (KUPAC_ID, RACUN_BROJ, RED_ID),
    
    -- STRANI KLJUC NA RACUNI
    CONSTRAINT FK_RED_RACUN FOREIGN KEY (KUPAC_ID, RACUN_BROJ) 
        REFERENCES RACUNI (KUPAC_ID, RACUN_BROJ),
    
    -- PROVJERE OGRANICENJA
    CONSTRAINT CHK_RED_STATUS CHECK (STATUS IN ('C', 'U', 'N', 'P')),
    CONSTRAINT CHK_RED_TRN_KOD CHECK (KOD_TRANSAKCIJE IN ('UPL', 'ISP', 'PRE', 'NAK', 'KAM', 'PRI')),
    CONSTRAINT CHK_RED_IZVOR CHECK (IZVORNI_SUSTAV IN ('BAN', 'SLU', 'WEB', 'ACH', 'TEL', 'LOT')),
    CONSTRAINT CHK_BROJ_PONOVNIH CHECK (BROJ_PONOVNIH >= 0 AND BROJ_PONOVNIH <= 5),
    CONSTRAINT CHK_KUPAC_ID_RED CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);

-- KREIRANJE INDEKSA ZA RED_TRANSAKCIJA
CREATE INDEX IDX_RED_VRIJEME ON RED_TRANSAKCIJA (VRIJEME_ZAPRIMLJENO);
CREATE INDEX IDX_RED_OBRADA ON RED_TRANSAKCIJA (DATUM_OBRADE);
CREATE INDEX IDX_RED_STATUS ON RED_TRANSAKCIJA (STATUS);
CREATE INDEX IDX_RED_IZVOR ON RED_TRANSAKCIJA (IZVORNI_SUSTAV);