-- =====================================================
-- TRANSAKCIJE TABLICA - POVIJEST TRANSAKCIJA
-- =====================================================
CREATE TABLE TRANSAKCIJE (
    KUPAC_ID            BIGINT          NOT NULL,
    RACUN_BROJ          CHAR(12)        NOT NULL,
    TRANSAKCIJA_ID      CHAR(20)        NOT NULL,
    KOD_TRANSAKCIJE     CHAR(4)         NOT NULL,
    IZNOS               DECIMAL(15,2)   NOT NULL,
    DATUM_TRANSAKCIJE   DATE            NOT NULL,
    DATUM_KNJIZENJA     DATE            NOT NULL,
    OPIS                VARCHAR(50),
    POZIV_NA_BROJ       VARCHAR(20),
    TEKUCI_SALDO        DECIMAL(15,2)   NOT NULL,
    IZVORNI_SUSTAV      CHAR(6)         NOT NULL,
    STATUS              CHAR(1)         DEFAULT 'K',
    VREMENSKI_ZAPIS     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    
    -- PRIMARNI I SEKUNDARNI KLJUCEVI
    CONSTRAINT PK_TRANSAKCIJE PRIMARY KEY (KUPAC_ID, RACUN_BROJ, TRANSAKCIJA_ID),
    
    -- STRANI KLJUC NA RACUNI
    CONSTRAINT FK_TRANSAKCIJE_RACUN FOREIGN KEY (KUPAC_ID, RACUN_BROJ) 
        REFERENCES RACUNI (KUPAC_ID, RACUN_BROJ),
    
    -- PROVJERE OGRANICENJA
    CONSTRAINT CHK_TRN_STATUS CHECK (STATUS IN ('K', 'P', 'O', 'G')),
    CONSTRAINT CHK_TRN_KOD CHECK (KOD_TRANSAKCIJE IN ('UPL', 'ISP', 'PRE', 'NAK', 'KAM', 'PRI', 'STO')),
    CONSTRAINT CHK_IZVORNI_SUS CHECK (IZVORNI_SUSTAV IN ('BAN', 'SLU', 'WEB', 'ACH', 'TEL', 'LOT')),
    CONSTRAINT CHK_KUPAC_ID_TRANSAKCIJE CHECK (KUPAC_ID BETWEEN 100000000000 AND 999999999999)
);

-- KREIRANJE INDEKSA ZA TRANSAKCIJE
CREATE INDEX IDX_TRANSAKCIJE_DATUM ON TRANSAKCIJE (DATUM_TRANSAKCIJE);
CREATE INDEX IDX_TRANSAKCIJE_KNJIZENJE ON TRANSAKCIJE (DATUM_KNJIZENJA);
CREATE INDEX IDX_TRANSAKCIJE_KOD ON TRANSAKCIJE (KOD_TRANSAKCIJE);
CREATE INDEX IDX_TRANSAKCIJE_STATUS ON TRANSAKCIJE (STATUS);
CREATE INDEX IDX_TRANSAKCIJE_IZVOR ON TRANSAKCIJE (IZVORNI_SUSTAV);