-- =====================================================
-- KREIRANJE SEKVENCI
-- =====================================================
SET CURRENT SCHEMA = 'BANKING_TEST';

CREATE SEQUENCE SEQ_KUPAC_ID
    AS BIGINT
    START WITH 100000000000
    INCREMENT BY 1
    MAXVALUE 999999999999
    NO CYCLE
    CACHE 1000
    ORDER;

CREATE SEQUENCE SEQ_TRANSAKCIJA_ID
    AS BIGINT
    START WITH 1000000000
    INCREMENT BY 1
    NO CYCLE
    CACHE 500
    ORDER;

CREATE SEQUENCE SEQ_BLOKADA_ID
    AS BIGINT
    START WITH 1000000
    INCREMENT BY 1
    NO CYCLE
    CACHE 50
    ORDER;

CREATE SEQUENCE SEQ_UNOS_GK_ID
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 1000
    ORDER;

CREATE SEQUENCE SEQ_RED_ID
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 200
    ORDER;

CREATE SEQUENCE SEQ_ADRESA_ID
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 100
    ORDER;

CREATE SEQUENCE SEQ_KONTAKT_ID
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 100
    ORDER;

CREATE SEQUENCE SEQ_DOKUMENT_ID
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 50
    ORDER;

CREATE SEQUENCE SEQ_STOPA_ID
    AS BIGINT
    START WITH 1
    INCREMENT BY 1
    NO CYCLE
    CACHE 100
    ORDER;