-- IZVORNI SUSTAVI
SET CURRENT SCHEMA = 'BANKING_TEST';

CREATE TABLESPACE TSIZVOR IN "BANKTEST" USING STOGROUP SYSDEFLT;

CREATE TABLE IZVORNI_SUSTAV_REF (
    SUSTAV_KOD          CHAR(3)         NOT NULL,
    NAZIV_SUSTAVA       VARCHAR(30)     NOT NULL,
    OPIS_SUSTAVA        VARCHAR(100),
    SIGURNOSNA_RAZINA   SMALLINT        DEFAULT 1,
    STATUS              CHAR(1)         DEFAULT 'A',

    CONSTRAINT PK_IZVORNI_SUSTAV PRIMARY KEY (SUSTAV_KOD),
    CONSTRAINT CHK_SUSTAV_SIGURNOST CHECK (SIGURNOSNA_RAZINA BETWEEN 1 AND 5),
    CONSTRAINT CHK_SUSTAV_STATUS CHECK (STATUS IN ('A', 'N'))
) IN BANKTEST.TSIZVOR;
