-- POSLOVNICE - ORGANIZACIJSKA STRUKTURA
SET CURRENT SCHEMA = 'BANKING_TEST';

CREATE TABLE POSLOVNICE (
    POSLOVNICA_KOD      CHAR(4)         NOT NULL,
    NAZIV_POSLOVNICE    VARCHAR(50)     NOT NULL,
    ADRESA              VARCHAR(100)    NOT NULL,
    GRAD                VARCHAR(30)     NOT NULL,
    POSTANSKI_BROJ      CHAR(5)         NOT NULL,
    TELEFON             VARCHAR(15),
    STATUS              CHAR(1)         DEFAULT 'A',
    DATUM_OTVARANJA     DATE            NOT NULL,
    
    CONSTRAINT PK_POSLOVNICE PRIMARY KEY (POSLOVNICA_KOD),
    CONSTRAINT CHK_POSLOVNICA_STATUS CHECK (STATUS IN ('A', 'Z', 'S'))
) IN BANKTEST.TSBANREF;