-- RIZIK OCJENE - STANDARDIZIRANE VRIJEDNOSTI
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE TABLESPACE TSRIZIK IN "BANKTEST" USING STOGROUP SYSDEFLT;
CREATE TABLE RIZIK_OCJENA_REF (
    RIZIK_KOD           CHAR(2)         NOT NULL,
    NAZIV_RIZIKA        VARCHAR(30)     NOT NULL,
    OPIS_RIZIKA         VARCHAR(100),
    FAKTOR_RIZIKA       DECIMAL(3,2)    DEFAULT 1.00,
    STATUS              CHAR(1)         DEFAULT 'A',
    
    CONSTRAINT PK_RIZIK_OCJENA PRIMARY KEY (RIZIK_KOD),
    CONSTRAINT CHK_RIZIK_STATUS CHECK 
     (STATUS IN ('A', 'N'))
) IN BANKTEST.TSRIZIK;
