-- STATUS REFERENCE - STANDARDIZIRANI STATUSI
SET CURRENT SCHEMA = 'BANKING_TEST';

CREATE TABLE STATUS_REF (
    STATUS_KOD          CHAR(1)         NOT NULL,
    NAZIV_STATUSA       VARCHAR(20)     NOT NULL,
    OPIS_STATUSA        VARCHAR(50),
    STATUS_KATEGORIJA   VARCHAR(20)     NOT NULL,
    
    CONSTRAINT PK_STATUS_REF PRIMARY KEY (STATUS_KOD, STATUS_KATEGORIJA)
) IN BANKTEST.TSBANREF;