-- TIP RACUNA - STANDARDIZIRANI TIPOVI
SET CURRENT SCHEMA = 'BANKING_TEST';
CREATE TABLESPACE TSTIPRAC IN "BANKTEST" USING STOGROUP SYSDEFLT;
CREATE TABLE TIP_RACUNA_REF (
    TIP_KOD             CHAR(3)         NOT NULL,
    NAZIV_TIPA          VARCHAR(30)     NOT NULL,
    OPIS_TIPA           VARCHAR(100),
    KAMATA_NOSIVA       CHAR(1)         DEFAULT 'N',
    MINUS_DOZVOLJEN     CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    
    CONSTRAINT PK_TIP_RACUNA PRIMARY KEY (TIP_KOD),
    CONSTRAINT CHK_TIP_KAMATA CHECK 
     (KAMATA_NOSIVA IN ('D', 'N')),
    CONSTRAINT CHK_TIP_MINUS CHECK 
     (MINUS_DOZVOLJEN IN ('D', 'N')),
    CONSTRAINT CHK_TIP_STATUS CHECK 
     (STATUS IN ('A', 'N'))
) IN BANKTEST.TSTIPRAC;