-- TRANSAKCIJSKI TIPOVI
SET CURRENT SCHEMA = 'BANKING_TEST';


CREATE TABLE TRANSAKCIJA_TIP_REF (
    TRN_TIP_KOD         CHAR(4)         NOT NULL,
    NAZIV_TIPA          VARCHAR(30)     NOT NULL,
    OPIS_TIPA           VARCHAR(100),
    SMJER_SALDA         CHAR(1)         NOT NULL,
    NAKNADA_PRIMJENJIVA CHAR(1)         DEFAULT 'N',
    STATUS              CHAR(1)         DEFAULT 'A',
    
    CONSTRAINT PK_TRANSAKCIJA_TIP PRIMARY KEY (TRN_TIP_KOD),
    CONSTRAINT CHK_TRN_SMJER CHECK (SMJER_SALDA IN ('+', '-', '=')),
    CONSTRAINT CHK_TRN_NAKNADA CHECK (NAKNADA_PRIMJENJIVA IN ('D', 'N')),
    CONSTRAINT CHK_TRN_STATUS CHECK (STATUS IN ('A', 'N'))
);